# -*- coding: utf-8 -*-

{
    'archetype':{
        'job id':{
            'name':u'Job ID',
            'keyword':u'job_id',
            'type':'int',
        },
        'department id':{
            'name':u'Department ID',
            'keyword':u'department_id',
            'type':'int',
        },

        'home id':{
            'name':u'Home ID',
            'keyword':u'home_id',
            'type':'int',
        },
        
        'album id':{
            'name':u'Album ID',
            'keyword':u'album_id',
            'type':'int',
        },
        'track id':{
            'name':u'Track ID',
            'keyword':u'track_id',
            'type':'int',
        },
        
        'tv show id':{
            'name':u'TV show ID',
            'keyword':u'tv_show_id',
            'type':'int',
        },
        'tv season id':{
            'name':u'TV season ID',
            'keyword':u'tv_season_id',
            'type':'int',
        },
        'tv episode id':{
            'name':u'TV episode ID',
            'keyword':u'tv_episode_id',
            'type':'int',
        },
        
        'movie id':{
            'name':u'Movie ID',
            'keyword':u'movie_id',
            'type':'int',
        },
        
        'collection id':{
            'name':u'Collection ID',
            'keyword':u'collection_id',
            'type':'int',
        },
        'person id':{
            'name':u'Person ID',
            'keyword':u'person_id',
            'type':'int',
        },
        'character id':{
            'name':u'Character ID',
            'keyword':u'character_id',
            'type':'int',
        },
        'company id':{
            'name':u'Company ID',
            'keyword':u'company_id',
            'type':'int',
        },
        'keyword id':{
            'name':u'Keyword ID',
            'keyword':u'keyword_id',
            'type':'int',
        },
        'genre id':{
            'name':u'Genre ID',
            'keyword':u'genre_id',
            'type':'int',
        },

        'home uri':{
            'name':u'Home URI',
            'keyword':'home_uri',
            'type':'unicode',
        },
        'asset uri':{
            'name':u'Asset URI',
            'keyword':'asset_uri',
            'type':'unicode',
        },
        'resource uri':{
            'name':u'Resource URI',
            'keyword':'resource_uri',
            'type':'unicode',
        },
    
        'itunes person id':{
            'name':u'iTunes person ID',
            'keyword':u'itunes_person_id',
            'type':'int',
            'atom':'atID',
        },
        'itunes movie id':{
            'name':u'iTunes movie ID',
            'keyword':u'itunes_movie_id',
            'type':'int',
        },
        'itunes tv show id':{
            'name':u'iTunes TV show ID',
            'keyword':u'itunes_tv_show_id',
            'type':'int',
        },
        'itunes tv season id':{
            'name':u'iTunes TV season ID',
            'keyword':u'itunes_tv_season_id',
            'type':'int',
        },
        'itunes tv episode id':{
            'name':u'iTunes TV episode ID',
            'keyword':u'itunes_tv_episode_id',
            'type':'int',
        },
        'itunes music album id':{
            'name':u'iTunes album ID',
            'keyword':u'itunes_music_album_id',
            'type':'int',
        }, 
        'itunes music track id':{
            'name':u'iTunes music track ID',
            'keyword':u'itunes_music_track_id',
            'type':'int',
        }, 
        'itunes content id':{
            'name':u'iTunes content ID',
            'keyword':u'itunes_content_id',
            'type':'int',
            'atom':'cnID',
        },
        'itunes composer id':{
            'name':u'iTunes composer ID',
            'keyword':u'itunes_composer_id',
            'type':'int',
            'atom':'cmID',
        },
        'itunes playlist id':{
            'name':u'iTunes playlist ID',
            'keyword':u'itunes_playlist_id',
            'type':'int',
            'atom':'plID',
        },
        'itunes genre id':{
            'name':u'iTunes genre ID',
            'keyword':u'itunes_genre_id',
            'type':'int',
            'atom':'geID',
        },
        'itunes country id':{
            'name':u'iTunes country ID',
            'keyword':u'itunes_country_id',
            'type':'enum',
            'atom':'sfID',
            'enumeration':'country',
        },
        'itunes account':{
            'name':u'iTunes account ID',
            'keyword':u'itunes_account_id',
            'type':'unicode',
            'atom':'apID',
        },
        'itunes account type':{
            'name':u'iTunes account type',
            'keyword':u'itunes_account_type',
            'type':'enum',
            'atom':'akID',
            'enumeration':'itunes account type',
        },
        'itunes episode global id':{
            'name':u'Episode global ID',
            'keyword':u'episode_global_id',
            'type':'int',
            'atom':'egid',
        },
        'xid':{
            'name':u'iTunes extra ID',
            'keyword':u'xid',
            'type':'unicode',
            'atom':'xid',
        },
        
        'tvdb person id':{
            'name':u'TVDb person ID',
            'keyword':u'tvdb_person_id',
            'type':'int',
        },
        'tvdb tv show id':{
            'name':u'TVDb TV show ID',
            'keyword':u'tvdb_tv_show_id',
            'type':'int',
        },
        'tvdb tv season id':{
            'name':u'TVDb TV season ID',
            'keyword':u'tvdb_tv_season_id',
            'type':'int',
        },
        'tvdb tv episode id':{
            'name':u'TVDb TV episode ID',
            'keyword':u'tvdb_tv_episode_id',
            'type':'int',
        },
        'tvdb image id':{
            'name':u'TVDb image ID',
            'keyword':u'tvdb_image_id',
            'type':'int',
        },
        
        'imdb person id':{
            'name':u'IMDb person ID',
            'keyword':u'imdb_person_id',
            'type':'unicode'
        },
        'imdb character id':{
            'name':u'IMDb character ID',
            'keyword':u'imdb_character_id',
            'type':'unicode'
        },
        'imdb movie id':{
            'name':u'IMDb movie ID',
            'keyword':u'imdb_movie_id',
            'type':'unicode'
        },
        'imdb tv show id':{
            'name':u'IMDb TV show ID',
            'keyword':u'imdb_tv_show_id',
            'type':'unicode',
        },
        'imdb tv episode id':{
            'name':u'IMDb TV episode ID',
            'keyword':u'imdb_tv_episode_id',
            'type':'unicode',
        },
        'trimmed imdb movie id':{
            'name':u'Trimmed IMDb movie ID',
            'keyword':u'trimmed_imdb_movie_id',
            'type':'unicode'
        },

        'tmdb movie id':{
            'name':u'TMDb movie ID',
            'keyword':u'tmdb_movie_id',
            'type':'int',
        },
        'tmdb collection id':{
            'name':u'TMDb collection ID',
            'keyword':u'tmdb_collection_id',
            'type':'int'
        },
        'tmdb person id':{
            'name':u'TMDb person ID',
            'keyword':u'tmdb_person_id',
            'type':'int',
        },
        'tmdb company id':{
            'name':u'TMDb company ID',
            'keyword':u'tmdb_company_id',
            'type':'int',
        },
        'tmdb genre id':{
            'name':u'TMDb genre ID',
            'keyword':u'tmdb_genre_id',
            'type':'int',
        },
        'tmdb keyword id':{
            'name':u'TMDb keyword ID',
            'keyword':u'tmdb_keyword_id',
            'type':'int',
        },
        'tmdb popularity':{
            'name':u'TMDb popularity score',
            'keyword':u'tmdb_popularity',
            'type':'float',
        },

        'rottentomatoes movie id':{
            'name':u'Rotten tomatoes movie ID',
            'keyword':u'rottentomatoes_movie_id',
            'type':'int',
        },
        'zap2it tv show id':{
            'name':u'Zap2It TV show ID',
            'keyword':u'zap2it_tv_show_id',
            'type':'unicode',
        },

        'country code':{
            'name':u'ISO 3166-1 alpha-2 country code',
            'keyword':u'country_code',
            'type':'enum',
            'enumeration':'country',
        },        
        'language code':{
            'name':u'ISO 639-1 language code',
            'keyword':u'language_code',
            'type':'enum',
            'enumeration':'language',
        },        

        'country name':{
            'name':u'Country name',
            'keyword':u'country_name',
            'type':'unicode',
        },        
        'native country name':{
            'name':u'Native country name',
            'keyword':u'native_country_name',
            'type':'unicode',
        },        
        'language name':{
            'name':u'Language name',
            'keyword':u'language_name',
            'type':'unicode',
        },        
        'native language name':{
            'name':u'Native language name',
            'keyword':u'native_language_name',
            'type':'unicode',
        },
        'genre name':{
            'name':u'Genre name',
            'keyword':u'genre_name',
            'type':'unicode',
            'atom':'©gen',
        },        
        'keyword name':{
            'name':u'Keyword name',
            'keyword':u'keyword_name',
            'type':'unicode',
        },
        'collection name':{
            'name':u'Collection name',
            'keyword':u'collection_name',
            'type':'unicode',
        },
        'company name':{
            'name':u'Company name',
            'keyword':u'company_name',
            'type':'unicode',
        },
        'person name':{
            'name':u'Person name',
            'keyword':u'person_name',
            'type':'unicode',
        },
        'character name':{
            'name':u'Character name',
            'keyword':u'character_name',
            'type':'unicode',
        },
        'tv show name':{
            'name':u'TV show name',
            'keyword':u'tv_show_name',
            'type':'unicode',
            'atom':'tvsh',
        },
        'tv episode name':{
            'name':u'TV episode name',
            'keyword':u'tv_episode_name',
            'type':'unicode',
        },
        'movie title':{
            'name':u'Movie title',
            'keyword':u'movie title',
            'type':'unicode',
        },
        'original movie title':{
            'name':u'Original movie title',
            'keyword':u'original_movie_title',
            'type':'unicode',
        },
        'music album name':{
            'name':u'Music album name',
            'keyword':u'music_album_name',
            'type':'unicode',
        },
        'music track name':{
            'name':u'Music track name',
            'keyword':u'music_track_name',
            'type':'unicode',
        },
        
        'critic name':{
            'name':u'Critic name',
            'keyword':u'critic_name',
            'type':'unicode',
        },
        'album name':{
            'name':u'Album name',
            'keyword':u'album_name',
            'type':'unicode',
            'atom':'©alb',
        },
        'track name':{
            'name':u'Track name',
            'keyword':u'track_name',
            'type':'unicode',
            'atom':'©nam',
        },
        'artist name':{
            'name':u'Artist',
            'keyword':u'artist_name',
            'type':'unicode',
            'atom':'@ART',
        },
        'composer name':{
            'name':u'Composer',
            'keyword':u'composer_name',
            'type':'unicode',
            'atom':'©wrt',
        },
        'album artist name':{
            'name':u'Album artist',
            'description':u'Artist for the whole album, if different than the individual tracks.',
            'keyword':u'album_artist_name',
            'type':'unicode',
            'atom':'aART',
        },
        'tv network name':{
            'name':u'TV network',
            'keyword':u'tv_network',
            'type':'unicode',
            'atom':'tvnn',
        },
        
        'simple keyword name':{
            'name':u'Simple keyword name',
            'keyword':u'simple_keyword_name',
            'type':'unicode',
            'simplify':True,
        },
        'simple collection name':{
            'name':u'Simple collection name',
            'keyword':u'simple_collection_name',
            'type':'unicode',
            'simplify':True,
        },
        'simple company name':{
            'name':u'Simple company name',
            'keyword':u'simple_company_name',
            'type':'unicode',
            'simplify':True,
        },
        'simple person name':{
            'name':u'Simple person name',
            'keyword':u'simple_person_name',
            'type':'unicode',
            'simplify':True,
        },
        'simple genre name':{
            'name':u'Simple genre name',
            'keyword':u'simple_genre_name',
            'type':'unicode',
            'simplify':True,
        },
        'simple character name':{
            'name':u'Simple character name',
            'keyword':u'simple_character_name',
            'type':'unicode',
            'simplify':True,
        },
        'simple tv show name':{
            'name':u'Simple tv show name',
            'keyword':u'simple_tv_show_name',
            'type':'unicode',
            'simplify':True,
        },
        'simple tv episode name':{
            'name':u'Simple tv episode name',
            'keyword':u'simple_tv_episode_name',
            'type':'unicode',
            'simplify':True,
        },
        'simple movie title':{
            'name':u'Simple movie title',
            'keyword':u'simple_movie_title',
            'type':'unicode',
            'simplify':True,
        },
        'simple music album name':{
            'name':u'Simple music album name',
            'keyword':u'simple_music_album_name',
            'type':'unicode',
            'simplify':True,
        },
        'simple music track name':{
            'name':u'Simple music track name',
            'keyword':u'simple_music_track_name',
            'type':'unicode',
            'simplify':True,
        },
        
        'simple name':{
            'name':u'Simple name',
            'keyword':u'simple_name',
            'type':'unicode',
            'simplify':True,
        },
        
        'sort name':{
            'name':u'Sort name',
            'keyword':u'sort_name',
            'type':'unicode',
            'atom':'sonm',
        },
        'sort artist':{
            'name':u'Sort artist',
            'keyword':u'sort_artist',
            'type':'unicode',
            'atom':'soar',
        },
        'sort composer':{
            'name':u'Sort composer',
            'keyword':u'sort_composer',
            'type':'unicode',
            'atom':'soco',
        },
        'sort album artist':{
            'name':u'Sort album artist',
            'keyword':u'sort_album_artist',
            'type':'unicode',
            'atom':'soaa',
        },
        'sort album':{
            'name':u'Sort album',
            'keyword':u'sort_album',
            'type':'unicode',
            'atom':'soal',
        },
        'sort tv show':{
            'name':u'Sort TV show',
            'keyword':u'sort_tv_show',
            'type':'unicode',
            'atom':'sosn',
        },

        'simple name':{
            'name':u'Simple name',
            'keyword':u'simple_name',
            'type':'unicode',
            'simplify':True,
        },
        'movie handle':{
            'name':u'Movie handle',
            'keyword':u'movie_handle',
            'type':'unicode',
            'simplify':True,
        },
        'album handle':{
            'name':u'Album handle',
            'keyword':u'album_handle',
            'type':'unicode',
            'simplify':True,
        },
        'tv show handle':{
            'name':u'TV show handle',
            'keyword':u'tv_show_handle',
            'type':'unicode',
            'simplify':True,
        },

        'track number':{
            'name':u'Track number',
            'keyword':u'track_number',
            'type':'int',
        },
        'track count':{
            'name':u'Track count',
            'keyword':u'track_count',
            'type':'int',
        },
        'track position':{
            'name':u'Track position',
            'keyword':u'track_position',
            'type':'unicode',
            'atom':'trkn',
        },
        'disc number':{
            'name':u'Disc number',
            'keyword':u'disc_number',
            'type':'int',
        },
        'disc count':{
            'name':u'Disc count',
            'keyword':u'disc_count',
            'type':'int',
        },
        'disc position':{
            'name':u'Disc position',
            'keyword':u'disc_position',
            'type':'unicode',
            'atom':'disk',
        },
        'tv season number':{
            'name':u'TV season number',
            'keyword':u'tv_season_number',
            'type':'int',
            'atom':'tvsn',
        },
        'tv episode number':{
            'name':u'TV episode number',
            'keyword':u'tv_episode_number',
            'type':'int',
            'atom':'tves',
        },
        'absolute tv episode number':{
            'name':u'Absolute TV episode',
            'keyword':'absolute_tv_episode',
            'type':'int',
        },
        'tv episode production code':{
            'name':u'TV episode production code',
            'keyword':u'tv_episode_production_code',
            'type':'unicode',
            'atom':'tven',
        },
        'track genealogy':{
            'name':u'Track genealogy',
            'keyword':u'track_genealogy',
            'type':'unicode',
        },
        
        'character encoding':{
            'name':u'Character encoding',
            'keyword':u'character_encoding',
            'type':'unicode',
        },
        'url':{
            'name':u'URL',
            'keyword':u'url',
            'type':'unicode',
        },
        'scheme':{
            'name':u'Scheme',
            'keyword':u'scheme',
            'type':'unicode',
        },
        'domain':{
            'name':u'Domain',
            'keyword':u'domain',
            'type':'unicode',
        },
        'host':{
            'name':u'Host',
            'keyword':u'host',
            'type':'unicode',
        },
        'port':{
            'name':u'Port',
            'keyword':u'port',
            'type':'int',
        },
        'path':{
            'name':u'Path',
            'keyword':u'path',
            'type':'unicode',
        },
        'path digest':{
            'name':u'Path SHA1',
            'keyword':u'path_digest',
            'type':'unicode',
        },
        'directory':{
            'name':u'Directory',
            'keyword':u'directory',
            'type':'unicode',
        },
        'file name':{
            'name':u'File name',
            'keyword':u'file_name',
            'type':'unicode',
        },
        'exploded path':{
            'name':u'Exploded path',
            'keyword':u'exploded_path',
            'type':'unicode',
        },
        'file size':{
            'name':u'File size',
            'keyword':u'file_size',
            'type':'int',
            'format':'byte',
        },
        'preset':{
            'name':u'Preset',
            'keyword':u'Preset',
            'type':'unicode'
        },
        'profile':{
            'name':u'Profile',
            'keyword':u'profile',
            'type':'unicode'
        },
        'volume':{
            'name':u'Volume',
            'keyword':u'volume',
            'type':'unicode'
        },
        'volume path':{
            'name':u'Volume path',
            'keyword':u'volume_path',
            'type':'unicode'
        },
        'kind':{
            'name':u'Kind',
            'keyword':u'kind',
            'type':'unicode',
        },
        'tv show status':{
            'name':u'TV show status',
            'keyword':u'tv_show_status',
            'type':'unicode',
        },
        'vote average':{
            'name':u'Vote average',
            'keyword':u'vote_average',
            'type':'float',
        },
        'vote count':{
            'name':'Vote count',
            'keyword':u'vote_count',
            'type':'int',
        },
        'language':{
            'name':u'Language',
            'keyword':u'language',
            'type':'enum',
            'enumeration':'language',
        },
        'media kind':{
            'name':u'Media kind',
            'keyword':u'media_kind',
            'type':'enum',
            'atom':'stik',
            'enumeration':'media kind',
        },
        'grouping':{
            'name':u'Grouping',
            'description':u'Overall work, like TIT1 in ID3',
            'keyword':u'grouping',
            'type':'unicode',
            'atom':'grup',
        },
        'comment':{
            'name':u'User comment',
            'keyword':u'comment',
            'type':'unicode',
            'atom':'©cmt',
        },
        'description':{
            'name':u'Description',
            'keyword':u'description',
            'type':'unicode',
            'atom':'desc',
        },
        'long description':{
            'name':u'Long description',
            'keyword':u'long_description',
            'type':'unicode',
            'atom':'ldes',
        },
        'biography':{
            'name':u'Biography',
            'keyword':u'biography',
            'type':'unicode',
        },
        'place of birth':{
            'name':u'Place of birth',
            'keyword':u'place_of_birth',
            'type':'unicode',
        },
        'lyrics':{
            'name':u'Lyrics',
            'keyword':u'lyrics',
            'type':'unicode',
            'atom':'©lyr',
        },
        'compilation':{
            'name':u'Compilation',
            'description':u'Is disc part of a compilation?',
            'keyword':u'compilation',
            'type':'bool',
            'atom':'cpil',
        },
        'copyright':{
            'name':u'Copyright',
            'keyword':u'copyright',
            'type':'unicode',
            'atom':'cprt',
        },
        'tempo':{
            'name':u'Beats per minute',
            'keyword':u'tempo',
            'type':'int',
            'atom':'tmpo',
        },
        'genre type':{
            'name':u'Pre-defined genre',
            'description':u'Enumerated value from ID3 tag set, plus 1',
            'keyword':u'genre_type',
            'type':'enum',
            'atom':'gnre',
            'enumeration':'genre',
        },
        'gapless':{
            'name':u'Gapless',
            'keyword':u'gapless',
            'type':'bool',
            'atom':'pgap',
        },
        'itunes keywords':{
            'name':u'iTunes keywords',
            'keyword':u'itunes_keywords',
            'type':'unicode',
            'atom':'keyw',
        },
        'itunes category':{
            'name':u'iTunes category',
            'keyword':u'itunes_category',
            'type':'unicode',
            'atom':'catg',
        },
        'hd video':{
            'name':u'HD video',
            'keyword':u'hd_video',
            'type':'int',
            'atom':'hdvd',
        },
        'encoding tool':{
            # mediainfo seems to mix @enc and @too into Encoded_Application
            'name':u'Encoding tool',
            'description':u'Software which encoded the recording',
            'keyword':u'encoding_tool',
            'type':'unicode',
            'atom':'©too',
        },
        'encoded by':{
            # mediainfo seems to mix @enc and @too into Encoded_Application
            'name':u'Encoded by',
            'description':u'Person or company that encoded the recording',
            'keyword':u'encoded_by',
            'type':'unicode',
            'atom':'@enc',
        },
        'modified date':{
            'name':u'Modified date',
            'keyword':u'modified_date',
            'type':'date',
        },
        'tag date':{
            'name':u'Tag date',
            'keyword':u'tag_date',
            'type':'date',
        },
        'birthday':{
            'name':u'Birthday',
            'keyword':u'birthday',
            'type':'date',
        },
        'deathday':{
            'name':u'Deathday',
            'keyword':u'deathday',
            'type':'date',
        },
        'release date':{
            'name':u'Release date',
            'keyword':u'release_date',
            'type':'date',
            'atom':'©day',
        },
        'purchase date':{
            'name':u'Purchase date',
            'keyword':u'purchase_date',
            'type':'date',
            'atom':'purd',
        },
        'encoded date':{
            'name':u'Encoded date',
            'keyword':u'encoded_date',
            'type':'date',
        },
        'podcast':{
            'name':u'Podcast',
            'keyword':u'podcast',
            'type':'bool',
            'atom':'pcst',
        },
        'podcast url':{
            'name':u'Podcast URL',
            'keyword':u'podcast_url',
            'type':'unicode',
            'atom':'purl',
        },
        'content rating':{
            'name':u'Content rating',
            'description':u'Does song have explicit content?',
            'keyword':u'content_rating',
            'type':'enum',
            'atom':'rtng',
            'enumeration':'content rating',
        },
        'itunnorm':{
            'name':u'iTunNORM',
            'description':'Sound Check analysis info',
            'keyword':u'itunnorm',
            'type':'unicode',
            'atom':'iTunNORM',
        },
        'itunextc':{
            'name':u'iTunEXTC',
            'keyword':u'itunextc',
            'type':'unicode',
            'atom':'iTunEXTC',
        },
        'itunmovi':{
            'name':u'iTunMOVI',
            'keyword':u'itunmovi',
            'type':'plist',
            'atom':'iTunMOVI',
        },
        'content advisory standard':{
            'name':u'Rating standard',
            'keyword':u'content_advisory_standard',
            'type':'unicode',
        },
        'content advisory rating':{
            'name':u'Rating',
            'keyword':u'content_advisory_rating',
            'type':'unicode',
        },
        'content advisory score':{
            'name':u'Rating score',
            'keyword':u'content_advisory_score',
            'type':'int',
        },
        'content advisory annotation':{
            'name':u'Rating annotation',
            'keyword':u'content_advisory_ annotation',
            'type':'unicode',
        },
        'cover':{
            'name':u'Cover art',
            'description':u'One or more cover art images',
            'keyword':u'cover_pieces',
            'type':'int',
            'atom':'covr',
            'auto cast':False,
        },
        'stream name':{
            'name':u'Stream name',
            'keyword':u'stream_name',
            'type':'unicode',
        },
        'stream type':{
            'name':u'Stream type',
            'keyword':u'stream_type',
            'type':'enum',
            'enumeration':'mediainfo stream type',
        },
        'stream kind':{
            'name':u'Stream kind',
            'keyword':u'stream_kind',
            'type':'enum',
            'enumeration':'stream kind',
        },
        'format':{
            'name':u'Format',
            'keyword':u'format',
            'type':'unicode',
        },
        'format profile':{
            'name':u'Format profile',
            'type':'unicode',
            'plural':'list',
        },
        'channel count':{
            'name':u'Channel count',
            'keyword':u'channel_count',
            'type':'int',
            'plural':'list',
        },
        'channel position':{
            'name':u'Channel position',
            'keyword':u'channel_position',
            'type':'unicode',
            'plural':'list',
        },
        'stream id':{
            'name':u'Stream ID',
            'keyword':u'stream_id',
            'type':'int',
        },
        'stream kind position':{
            'name':u'Stream position',
            'keyword':u'stream_kind_position',
            'type':'int',
        },
        'stream size':{
            'name':u'Stream size',
            'keyword':u'stream_size',
            'type':'int',
            'format':'byte',
        },
        'stream portion':{
            'name':u'Stream portion',
            'keyword':u'stream_portion',
            'type':'float',
        },
        'default':{
            'name':u'Default',
            'keyword':u'default',
            'type':'bool',
        },
        'primary':{
            'name':u'Primary',
            'keyword':u'primary',
            'type':'bool',
        },
        'delay':{
            'name':u'Delay',
            'keyword':u'delay',
            'type':'int',
        },
        'bit rate':{
            'name':u'Bit rate',
            'keyword':u'bit_rate',
            'type':'int',
            'format':'bitrate',
        },
        'bit rate mode':{
            'name':u'Bit rate mode',
            'keyword':u'bit_rate_mode',
            'type':'unicode',
        },
        'bit depth':{
            'name':u'Bit depth',
            'keyword':u'bit_depth',
            'type':'int',
            'format':'bit',
        },
        'sample rate':{
            'name':u'Sample rate',
            'keyword':u'sample_rate',
            'type':'int',
            'format':'frequency',
        },
        'sample count':{
            'name':u'Sample count',
            'keyword':u'sample_count',
            'type':'int',
        },
        'frame rate':{
            'name':u'Frame rate',
            'keyword':u'frame_rate',
            'type':'float',
            'format':'framerate',
        },
        'frame rate mode':{
            'name':u'Frame rate mode',
            'keyword':u'frame_rate_mode',
            'type':'unicode',
        },
        'frame rate minimum':{
            'name':u'Frame rate minimum',
            'keyword':u'frame_rate_minimum',
            'type':'float',
            'format':'framerate',
        },
        'frame rate maximum':{
            'name':u'Frame rate maximum',
            'keyword':u'frame_rate_maximum',
            'type':'float',
            'format':'framerate',
        },
        'frame count':{
            'name':u'Frame count',
            'keyword':u'frame_count',
            'type':'int',
        },
        'duration':{
            'name':u'Duration',
            'keyword':u'duration',
            'type':'int',
            'format':'millisecond',
        },
        'width':{
            'name':u'Width',
            'keyword':u'width',
            'type':'int',
            'format':'pixel',
        },
        'height':{
            'name':u'Height',
            'keyword':u'height',
            'type':'int',
            'format':'pixel',
        },
        'pixel aspect ratio':{
            'name':u'Pixel aspect ratio',
            'keyword':u'pixel_aspect_ratio',
            'type':'float',
        },
        'display aspect ratio':{
            'name':u'Display aspect ratio',
            'keyword':u'display_aspect_ratio',
            'type':'float',
        },
        'color space':{
            'name':u'Color space',
            'keyword':u'color_space',
            'type':'unicode',
        },
        'channels':{
            'name':u'Channels',
            'keyword':u'channels',
            'type':'int',
        },
        'dialnorm':{
            'name':u'Dialnorm',
            'keyword':u'dialnorm',
            'type':'int',
        },
        'bpf':{
            'name':u'Bits / Pixel * Frame',
            'keyword':u'bpf',
            'type':'float',
        },
        'encoder':{
            'name':u'Encoder',
            'keyword':u'encoder',
            'type':'unicode',
        },
        'encoder settings':{
            'name':u'Encoder settings',
            'keyword':u'encoder_settings',
            'type':'unicode',
            'plural':'dict',
        },
        'sort order':{
            'name':u'Sort order',
            'keyword':u'sort_order',
            'type':'int',
        },
        'tv show air day':{
            'name':u'TV show air day',
            'keyword':u'tv_show_air_day',
            'type':'unicode',
        },
        'tv show air time':{
            'name':u'TV show air time',
            'keyword':u'tv_show_air_time',
            'type':'unicode',
        },
        'track subtitle':{
            'name':'Track subtitle',
            'keyword':'track_subtitle',
            'type':'unicode',
            'atom':'@st3',
            'enable':False,
        },
        'art director':{
            'name':u'Art director',
            'description':'Person responsible for non-photographic artwork used with content',
            'keyword':u'art_director',
            'type':'unicode',
            'atom':'@ard',
            'enable':False,
        },
        'arranger':{
            'name':u'Arranger',
            'description':'Person responsible for particular adaptation of composition',
            'keyword':u'arranger',
            'type':'unicode',
            'atom':'@arg',
            'enable':False,
        },
        'lyricist':{
            'name':u'Lyricist',
            'description':u'Writer of the song lyrics',
            'keyword':'lyricist',
            'type':'unicode',
            'atom':'©aut',
            'enable':False,
        },
        'copyright acknowledgement':{
            'name':u'Copyright acknowledgement',
            'description':u'Ackowledgements of those granting permission to use copyrighted material',
            'keyword':'copyright_acknowledgement',
            'type':'unicode',
            'atom':'©cak',
            'enable':False,
        },
        'conductor':{
            'name':u'Conductor',
            'description':u'Name of the person who directed the orchestra',
            'keyword':'conductor',
            'type':'unicode',
            'atom':'©con',
            'enable':False,
        },
        'song description':{
            'name':u'Song description',
            'description':u'Explanation of the song',
            'keyword':'song_description',
            'type':'unicode',
            'atom':'©des',
            'enable':False,
        },
        'equalization preset name':{
            'name':u'Equalization preset name',
            'description':u'Setting for equalization of content',
            'keyword':'equalization_preset_name',
            'type':'unicode',
            'atom':'©equ',
            'enable':False,
        },
        'liner notes':{
            'name':u'Liner notes',
            'description':u'Explanatory notes about a record album, included on the jacket or in the packaging',
            'keyword':'liner_notes',
            'type':'unicode',
            'atom':'©lnt',
            'enable':False,
        },
        'record company':{
            'name':u'Record company',
            'description':u'Company releasing the song',
            'keyword':'record_company',
            'type':'unicode',
            'atom':'©mak',
            'enable':False,
        },
        'original artist':{
            'name':u'Original artist',
            'description':u'Name of artist originally attributed with content',
            'keyword':'original_artist',
            'type':'unicode',
            'atom':'©ope',
            'enable':False,
        },
        'phonogram rights':{
            'name':u'Phonogram rights',
            'description':u'Like a copyright, but using the circled P symbol, for audio rights',
            'keyword':'phonogram_rights',
            'type':'unicode',
            'atom':'©phg',
            'enable':False,
        },
        'performer':{
            'name':u'Performer',
            'description':u'Name or URL of the individual primary members of the band or group',
            'keyword':'Performer',
            'type':'unicode',
            'atom':'©prf',
            'enable':False,
        },
        'publisher':{
            'name':u'Publisher',
            'description':u'Company publishing the song',
            'keyword':'publisher',
            'type':'unicode',
            'atom':'©pub',
            'enable':False,
        },
        'sound engineer':{
            'name':u'Sound engineer',
            'description':u'The name of the person doing soundengineering',
            'keyword':'sound_engineer',
            'type':'unicode',
            'atom':'©sne',
            'enable':False,
        },
        'soloist':{
            'name':u'Soloist',
            'description':u'Name of the musician who performs the solo',
            'keyword':'soloist',
            'type':'unicode',
            'atom':'©sol',
            'enable':False,
        },
        'credits':{
            'name':u'Credits',
            'description':u'Credits for those who provided source content',
            'keyword':'credits',
            'type':'unicode',
            'atom':'©src',
            'enable':False,
        },
        'thanks':{
            'name':u'Thanks and dedications',
            'description':u'Notes of acknowledgement or recognition from the artist',
            'keyword':'thanks',
            'type':'unicode',
            'atom':'©thx',
            'enable':False,
        },
        'online extras':{
            'name':u'Online extras',
            'description':u'Links to content that can only be accessed when connected to the internet',
            'keyword':'online_extras',
            'type':'unicode',
            'atom':'©url',
            'enable':False,
        },
        'executive producer':{
            'name':u'Executive producer',
            'description':u'Person responsible for creating or supervising the song',
            'keyword':'executive_producer',
            'type':'unicode',
            'atom':'©xpd',
            'enable':False,
        },
        'producer':{
            'name':u'Producer',
            'description':u'Person responsible for creating or supervising the song',
            'keyword':'producer',
            'type':'unicode',
            'atom':'©prd',
            'enable':False,
        },
        'director':{
            'name':u'Director',
            'description':u'Name of director for movie',
            'keyword':'director',
            'type':'unicode',
            'atom':'©dir',
            'enable':False,
        },
        
        'homepage':{
            'name':u'Homepage',
            'keyword':u'homepage',
            'type':'unicode',
        },
        'tagline':{
            'name':u'Tagline',
            'keyword':u'tagline',
            'type':'unicode',
        },
        'budget':{
            'name':u'Budget',
            'keyword':u'budget',
            'type':'int',
        },
        'runtime':{
            'name':u'Runtime',
            'keyword':u'runtime',
            'type':'int',
        },
        'revenue':{
            'name':u'Revenue',
            'keyword':u'revenue',
            'type':'int',
        },
        
        'api key':{
            'name':u'API Key',
            'keyword':u'api_key',
            'type':'unicode',
        },
        'term':{
            'name':u'Term',
            'keyword':u'term',
            'type':'unicode',
        },
        'page':{
            'name':u'Page',
            'keyword':u'page',
            'type':'int',
        },
        'release year':{
            'name':u'Year',
            'keyword':u'release_year',
            'type':'int',
        },
        'recursive':{
            'name':u'Recursive',
            'keyword':u'recursive',
            'type':'bool',
        },
        'sync':{
            'name':u'Synchronize',
            'keyword':u'sync',
            'type':'bool',
        },
        'crawl':{
            'name':u'Crawl',
            'keyword':u'crawl',
            'type':'bool',
        },
        'download':{
            'name':u'Download',
            'keyword':u'download',
            'type':'bool',
        },
        'overwrite':{
            'name':u'Overwrite',
            'keyword':u'overwrite',
            'type':'bool',
        },
        'debug':{
            'name':u'Debug',
            'keyword':u'debug',
            'type':'bool',
        },
        'verbosity':{
            'name':u'Verbosity',
            'keyword':u'verbosity',
            'type':'enum',
            'enumeration':'verbosity',
        },
        'configuration path':{
            'name':u'Configuration path',
            'keyword':u'configuration_path',
            'type':'unicode',
        },
        'inclusion':{
            'name':u'Inclusion filter',
            'keyword':u'inclusion',
            'type':'unicode',
        },
        'exclusion':{
            'name':u'Exclusion filter',
            'keyword':u'exclusion',
            'type':'unicode',
        },
        'scan path':{
            'name':u'Scan path',
            'keyword':u'scan_path',
            'type':'unicode',
            'plural':'list',
        },
        'uris':{
            'name':u'URIs',
            'keyword':u'uris',
            'type':'unicode',
            'plural':'list',
        },
        'quantizer':{
            'name':u'Quantizer',
            'keyword':u'quantizer',
            'type':'float',
        },
        'crop':{
            'name':u'Crop',
            'keyword':u'crop',
            'type':'unicode',
        },
        'time shift':{
            'name':u'Time shift',
            'keyword':u'shift',
            'type':'int',
        },
        'source frame rate':{
            'name':u'Source frame rate',
            'keyword':u'source_frame_rate',
            'type':'enum',
            'enumeration':'frame rate',
        },
        'target frame rate':{
            'name':u'Target frame rate',
            'keyword':u'target_frame_rate',
            'type':'enum',
            'enumeration':'frame rate',
        },
        'action':{
            'name':u'Action',
            'keyword':u'action',
            'type':'unicode',
        },
        'handbrake parameters':{
            'name':u'HandBrake parameters',
            'keyword':u'handbrake_parameters',
            'type':'unicode',
            'plural':'dict',
        },
        'handbrake x264 settings':{
            'name':u'HandBrake x264 settings',
            'keyword':u'handbrake_x264_settings',
            'type':'unicode',
            'plural':'dict',
        },
        'handbrake audio encoder settings':{
            'name':u'HandBrake audio encoder settings',
            'keyword':u'handbrake_audio_encoder_settings',
            'type':'unicode',
            'plural':'dict',
        },
        
        'database':{
            'name':u'Database',
            'keyword':u'database',
            'type':'unicode',
        },
        'username':{
            'name':u'Username',
            'keyword':u'username',
            'type':'unicode',
        },
        'password':{
            'name':u'Password',
            'keyword':u'password',
            'type':'unicode',
        },
        'mongodb url':{
            'name':u'MongoDB URL',
            'keyword':u'mongodb_url',
            'type':'unicode',
        },

        'keywords':{
            'name':u'Keywords',
            'keyword':u'keywords',
            'type':'unicode',
            'plural':'list',
        },
        'actors':{
            'name':u'Actors',
            'type':'unicode',
            'keyword':u'actors',
            'plural':'list',
        },
        'directors':{
            'name':u'Directors',
            'keyword':u'directors',
            'type':'unicode',
            'plural':'list',
        },
        'codirectors':{
            'name':u'Codirectors',
            'keyword':u'codirectors',
            'type':'unicode',
            'plural':'list',
        },
        'producers':{
            'name':u'Producers',
            'keyword':u'producers',
            'type':'unicode',
            'plural':'list',
        },
        'screenwriters':{
            'name':u'Screenwriters',
            'keyword':u'screenwriters',
            'type':'unicode',
            'plural':'list',
        },
        'studio':{
            'name':u'Studio',
            'keyword':u'studio',
            'type':'unicode',
            'plural':'list',
        },
        'genres':{
            'name':'Genres',
            'keyword':'genres',
            'type':'embed',
            'namespace':'ns.knowledge.genre',
            'plural':'list',
        },
        'production companies':{
            'name':'Production companies',
            'keyword':'production_companies',
            'type':'embed',
            'namespace':'ns.knowledge.company',
            'plural':'list',
        },
        'production countries':{
            'name':'Production countries',
            'keyword':'production_countries',
            'type':'embed',
            'namespace':'ns.knowledge.country',
            'plural':'list',
        },
        'spoken languages':{
            'name':'Spoken languages',
            'keyword':'spoken_languages',
            'type':'embed',
            'namespace':'ns.knowledge.languages',
            'plural':'list',
        },
        'backdrops':{
            'name':'Backdrops',
            'keyword':'backdrops',
            'type':'embed',
            'namespace':'ns.knowledge.image',
            'plural':'list',
        },
        'posters':{
            'name':'Posters',
            'keyword':'posters',
            'type':'embed',
            'namespace':'ns.knowledge.image',
            'plural':'list',
        },
        'profiles':{
            'name':'Profiles',
            'keyword':'profiles',
            'type':'embed',
            'namespace':'ns.knowledge.image',
            'plural':'list',
        },
        'part of a collection':{
            'name':'part of a collection',
            'keyword':'part_of_a_collection',
            'type':'embed',
            'namespace':'ns.knowledge.collection',
        },
        'cast':{
            'name':'Cast',
            'keyword':'cast',
            'type':'embed',
            'namespace':'ns.knowledge.cast',
            'plural':'list',
        },
        'crew':{
            'name':'Crew',
            'keyword':'crew',
            'type':'embed',
            'namespace':'ns.knowledge.cast',
            'plural':'list',
        },
        'movies':{
            'name':'Movies',
            'keyword':'movies',
            'type':'embed',
            'namespace':'ns.knowledge.movie',
            'plural':'list',
        },
        'certifications':{
            'name':'Certification',
            'keyword':'certification',
            'type':'embed',
            'namespace':'ns.knowledge.certification',
            'plural':'list',
        },
        'titles':{
            'name':'Titles',
            'keyword':'titles',
            'type':'embed',
            'namespace':'ns.knowledge.movie',
            'plural':'list',
        },
        'reviews':{
            'name':'Reviews',
            'keyword':'reviews',
            'type':'embed',
            'namespace':'ns.knowledge.review',
            'plural':'list',
        },
        'critics consensus':{
            'name':u'Critics consensus',
            'keyword':u'critics_consensus',
            'type':'unicode',
        },
        'audience rating':{
            'name':u'Audience rating',
            'keyword':u'audience_rating',
            'type':'unicode',
        },
        'critics rating':{
            'name':u'Critics rating',
            'keyword':u'critics_rating',
            'type':'unicode',
        },
        'audience score':{
            'name':u'Audience score',
            'keyword':u'audience_score',
            'type':'int',
        },
        'critics score':{
            'name':u'Critics score',
            'keyword':u'critics_score',
            'type':'int',
        },
        'freshness':{
            'name':u'Freshness',
            'keyword':u'freshness',
            'type':'unicode',
        },
        'original critic score':{
            'name':u'Original critic score',
            'keyword':u'original critic score',
            'type':'unicode',
        },
        'review publication':{
            'name':u'Review publication',
            'keyword':u'review_publication',
            'type':'unicode',
        },
        'review quote':{
            'name':u'Review quote',
            'keyword':u'review_quote',
            'type':'unicode',
        },
        'review url':{
            'name':u'Review url',
            'keyword':u'review_url',
            'type':'unicode',
        },
        
        'image url':{
            'name':u'Image URL',
            'keyword':u'image_url',
            'type':'unicode',
        },
        'thumbnail url':{
            'name':u'Thumbnail URL',
            'keyword':u'thumbnail_url',
            'type':'unicode',
        },
        'poster url':{
            'name':u'Poster URL',
            'keyword':u'poster_url',
            'type':'unicode',
        },
        'backdrop url':{
            'name':u'Backdrop URL',
            'keyword':u'backdrop_url',
            'type':'unicode',
        },
        'profile url':{
            'name':u'Profile URL',
            'keyword':u'profile_url',
            'type':'unicode',
        },
        'banner url':{
            'name':u'Banner URL',
            'keyword':u'banner_url',
            'type':'unicode',
        },
        'fan art url':{
            'name':u'Fan Art URL',
            'keyword':u'fan_art_url',
            'type':'unicode',
        },
    },
}