# -*- coding: utf-8 -*-

info = {
    'file':(
        {
            'name':'encoding',
            'print':'Encoding',
            'type':unicode,
        },
        {
            'name':'file path',
            'print':'File path',
            'type':unicode,
        },
        {
            'name':'directory',
            'print':'Directory',
            'type':unicode,
            'display':False,
        },
        {
            'name':'file name',
            'print':'File name',
            'type':unicode,
            'display':False,
        },
        {
            'name':'kind',
            'print':'Kind',
            'type':unicode,
            'display':False,
        },
        {
            'name':'format',
            'print':'Format',
            'mediainfo':'Format',
            'type':unicode,
        },
        {
            'name':'size',
            'print':'Size',
            'mediainfo':'FileSize',
            'type':int,
            'format':'byte',
        },
    ),
    'tag':(
        {
            'name':'encode date',
            'print':'Encode Date',
            'mediainfo':'Encoded_Date',
            'type':'date'
        },
        {
            'name':'modified date',
            'print':'Modified Date',
            'mediainfo':'File_Modified_Date',
            'type':'date',
        },
        {
            'name':'tag date',
            'print':'Tag Date',
            'mediainfo':'Tagged_Date',
            'type':'date',
        },
        {
            'name':'duration',
            'print':'Duration',
            'mediainfo':'Duration',
            'type':int,
            'format':'millisecond',
        },
        {
            'name':'bit rate',
            'print':'Bit Rate',
            'mediainfo':'OverallBitRate',
            'type':int,
            'format':'bitrate',
        },
        {
            'name':'language',
            'print':'Language',
            'type':unicode
        },
        {
            'name':'profile',
            'print':'Profile',
            'type':unicode
        },
        {
            'name':'volume',
            'print':'Volume',
            'type':unicode
        },
        {
            'name':'imdb id',
            'keyword':'imdb_id',
            'print':'IMDb',
            'type':unicode
        },
        {
            'name':'kind',
            'keyword':'kind',
            'print':'Kind',
            'type':unicode,
        },
        {
            'name':'tv show key',
            'keyword':'tv_show_key',
            'print':'TV Show Key',
            'type':unicode,
        },
        {
            'name':'simple name',
            'keyword':'simple_name',
            'print':'Simple Name',
            'type':unicode,
        },
        {
            'name':'name',
            'atom':'©nam',
            'mediainfo':'Title',
            'subler':'Name',
            'print':'Name',
            'type':unicode,
        },
        {
            'name':'artist',
            'atom':'@ART',
            'mediainfo':'Performer',
            'subler':'Artist',
            'print':'Artist',
            'type':unicode,
        },
        {
            'name':'album artist',
            'atom':'aART',
            'mediainfo':'Album_Performer',
            'subler':'Album Artist',
            'print':'Album Artist',
            'type':unicode,
        },
        {
            'name':'album',
            'atom':'©alb',
            'mediainfo':'Album',
            'subler':'Album',
            'print':'Album',
            'type':unicode,
        },
        {
            'name':'grouping',
            'atom':'grup',
            'mediainfo':'Grouping',
            'subler':'Grouping',
            'print':'Grouping',
            'type':unicode,
        },
        {
            'name':'composer',
            'atom':'©wrt',
            'mediainfo':'ScreenplayBy',
            'subler':'Composer',
            'print':'Composer',
            'type':unicode,
        },
        {
            'name':'comment',
            'atom':'©cmt',
            'mediainfo':'Comment',
            'subler':'Comments',
            'print':'Comment',
            'type':unicode,
        },
        {
            'name':'genre type',
            'atom':'gnre',
            'mediainfo':None,
            'mp4info':'GenreType',
            'subler':None,
            'print':'Genre Type',
            'type':'enum',
        },
        {
            'name':'genre',
            'atom':'©gen',
            'mediainfo':None,
            'mp4info': 'Genre',
            'subler':'Genre',
            'print':'Genre',
            'type':unicode,
        },
        {
            'name':'release date',
            'atom':'©day',
            'mediainfo':'Recorded_Date',
            'subler':'Release Date',
            'print':'Release Date',
            'type':'date',
        },
        {
            'name':'tempo',
            'atom':'tmpo',
            'mediainfo':'BPM',
            'subler':'Tempo',
            'print':'Tempo',
            'type':int,
        },
        {
            'name':'compilation',
            'atom':'cpil',
            'mediainfo':'Compilation',
            'print':'Compilation',
            'type':bool
        },
        {
            'name':'tv show',
            'atom':'tvsh',
            'mediainfo':'tvsh',
            'subler':'TV Show',
            'print':'TV Show',
            'type':unicode,
        },
        {
            'name':'tv episode id',
            'atom':'tven',
            'mediainfo':'tven',
            'subler':'TV Episode ID',
            'print':'TV Episode ID',
            'type':unicode,
        },
        {
            'name':'tv season',
            'keyword':'tv_season',
            'atom':'tvsn',
            'mediainfo':'tvsn',
            'subler':'TV Season',
            'print':'TV Season',
            'type':int,
        },
        {
            'name':'tv episode #',
            'keyword':'tv_episode',
            'atom':'tves',
            'mediainfo':'tves',
            'subler':'TV Episode #',
            'print':'TV Episode',
            'type':int,
        },
        {
            'name':'tv network',
            'atom':'tvnn',
            'mediainfo':'tvnn',
            'subler':'TV Network',
            'print':'TV Network',
            'type':unicode,
        },
        {
            'name':'sort name',
            'keyword':'sort_name',
            'atom':'sonm',
            'mediainfo':'sonm',
            'subler':'Sort Name',
            'print':'Sort Name',
            'type':unicode,
            'display':False,
        },
        {
            'name':'sort artist',
            'keyword':'sort_artist',
            'atom':'soar',
            'mediainfo':'soar',
            'subler':'Sort Artist',
            'print':'Sort Artist',
            'type':unicode,
            'display':False,
        },
        {
            'name':'sort album artist',
            'keyword':'sort_album_artist',
            'atom':'soaa',
            'mediainfo':'soaa',
            'subler':'Sort Album Artist',
            'print':'Sort Album Artist',
            'type':unicode,
            'display':False,
        },
        {
            'name':'sort album',
            'keyword':'sort_album',
            'atom':'soal',
            'mediainfo':'soal',
            'subler':'Sort Album',
            'print':'Sort Album',
            'type':unicode,
            'display':False,
        },
        {
            'name':'sort composer',
            'keyword':'sort_composer',
            'atom':'soco',
            'mediainfo':'soco',
            'subler':'Sort Composer',
            'print':'Sort Composer',
            'type':unicode,
            'display':False,
        },
        {
            'name':'sort tv show',
            'keyword':'sort_tv_show',
            'atom':'sosn',
            'mediainfo':'sosn',
            'subler':'Sort TV Show',
            'print':'Sort TV Show',
            'type':unicode,
            'display':False,
        },
        {
            'name':'description',
            'atom':'desc',
            'mediainfo':'desc',
            'subler':'Description',
            'print':'Description',
            'type':unicode,
            'unescape xml':True,
        },
        {
            'name':'long description',
            'atom':'ldes',
            'mediainfo':'ldes',
            'subler':'Long Description',
            'print':'Long Description',
            'type':unicode,
            'unescape xml':True,
        },
        {
            'name':'lyrics',
            'atom':'©lyr',
            'mediainfo':None,
            'mp4info': 'Lyrics',
            'subler':'Lyrics',
            'print':'Lyrics',
            'type':unicode,
            'unescape xml':True,
        },
        {
            'name':'copyright',
            'atom':'cprt',
            'mediainfo':'Copyright',
            'subler':'Copyright',
            'print':'Copyright',
            'type':unicode,
        },
        {
            'name':'encoding tool',
            'atom':'©too',
            'mediainfo':None, # mediainfo seems to mix @enc and @too into Encoded_Application
            'mp4info': 'Encoded with',
            'subler':'Encoding Tool',
            'print':'Encoding Tool',
            'type':unicode,
        },
        {
            'name':'encoded by',
            'atom':'@enc',
            'mediainfo':None, # mediainfo seems to mix @enc and @too into Encoded_Application
            'mp4info': 'Encoded by',
            'subler':'Encoded by',
            'print':'Encoded by',
            'type':unicode,
            'display':False,
        },
        {
            'name':'purchase date',
            'atom':'purd',
            'mediainfo':'purd',
            'subler':'Purchase Date',
            'print':'Purchase Date',
            'type':'date',
        },
        {
            'name':'podcast',
            'atom':'pcst',
            'mediainfo':'pcst',
            'print':'Podcast',
            'type':bool
        },
        {
            'name':'podcast url',
            'atom':'purl',
            'print':'Podcast URL',
            'type':unicode,
        },
        {
            'name':'keywords',
            'atom':'keyw',
            'mediainfo':'keyw',
            'print':'Keywords',
            'type':unicode,
        },
        {
            'name':'category',
            'atom':'catg',
            'mediainfo':'catg',
            'print':'Category',
            'type':unicode,
        },
        {
            'name':'hd video',
            'atom':'hdvd',
            'mediainfo':'hdvd',
            'subler':'HD Video',
            'print':'HD Video',
            'type':bool
        },
        {
            'name':'gapless',
            'atom':'pgap',
            'mp4info': 'Part of Gapless Album',
            'subler':'Gapless',
            'print':'Gapless',
            'type':bool
        },
        {
            'name':'xid',
            'atom':'xid',
            'mediainfo':'xid',
            'subler':'XID',
            'print':'XID',
            'type':unicode,
        },
        {
            'name':'content id',
            'atom':'cnID',
            'mediainfo':'cnID',
            'subler':'contentID',
            'print':'Content ID',
            'type':int,
        },
        {
            'name':'itunes account',
            'atom':'apID',
            'mediainfo':'apID',
            'subler':'iTunes Account',
            'print':'iTunes Account',
            'type':unicode,
        },
        {
            'name':'artist id',
            'atom':'atID',
            'mediainfo':'atID',
            'print':'Artist ID',
            'type':int,
        },
        {
            'name':'composer id',
            'atom':'cmID',
            'mediainfo':'cmID',
            'print':'Composer ID',
            'type':int,
        },
        {
            'name':'playlist id',
            'atom':'plID',
            'mediainfo':'plID',
            'print':'Playlist ID',
            'type':int,
        },
        {
            'name':'genre id',
            'atom':'geID',
            'mediainfo':'geID',
            'print':'Genre ID',
            'type':int,
        },
        {
            'name':'itunes store country',
            'atom':'sfID',
            'mediainfo':'sfID',
            'print':'iTunes Store Country',
            'type':'enum',
        },
        {
            'name':'itunes account type',
            'atom':'akID',
            'mediainfo':'akID',
            'print':'iTunes Account Type',
            'type':'enum',
        },
        {
            'name':'episode global id',
            'atom':'egid',
            'print':'Episode Global ID',
            'type':int,
        },
        {
            'name':'media kind',
            'atom':'stik',
            'mediainfo':'stik',
            'subler':'Media Kind',
            'print':'Media Kind',
            'type':'enum',
        },
        {
            'name':'content rating',
            'atom':'rtng',
            'mediainfo':'rtng',
            'subler':'Content Rating',
            'print':'Content Rating',
            'type':'enum',
        },
        {
            'name':'itunextc',
            'atom':'iTunEXTC',
            'mediainfo':'iTunEXTC',
            'print':'iTunEXTC',
            'type':unicode,
            'display':False
        },
        {
            'name':'itunmovi',
            'atom':'iTunMOVI',
            'mediainfo':'iTunMOVI',
            'print':'iTunMOVI',
            'type':'plist',
            'display':False
        },
        {
            'name':'cast',
            'atom':'iTunMOVI',
            'subler':'Cast',
            'print':'Cast',
            'type':unicode,
            'plural':'list',
        },
        {
            'name':'directors',
            'atom':'iTunMOVI',
            'subler':'Director',
            'print':'Directors',
            'type':unicode,
            'plural':'list',
        },
        {
            'name':'codirectors',
            'atom':'iTunMOVI',
            'subler':'Codirectors',
            'print':'Codirectors',
            'type':unicode,
            'plural':'list',
        },
        {
            'name':'producers',
            'atom':'iTunMOVI',
            'subler':'Producers',
            'print':'Producers',
            'type':unicode,
            'plural':'list',
        },
        {
            'name':'screenwriters',
            'atom':'iTunMOVI',
            'subler':'Screenwriters',
            'print':'Screenwriters',
            'type':unicode,
            'plural':'list',
        },
        {
            'name':'studio',
            'atom':'iTunMOVI',
            'subler':'Studio',
            'print':'Studio',
            'type':unicode,
            'plural':'list',
        },
        {
            'name':'rating standard',
            'keyword':'rating_standard',
            'atom':'iTunEXTC',
            'print':'Rating Standard',
            'type':unicode,
            'display':False,
        },
        {
            'name':'rating',
            'keyword':'rating',
            'atom':'iTunEXTC',
            'subler':'Rating',
            'print':'Rating',
            'type':unicode,
        },
        {
            'name':'rating score',
            'keyword':'rating_score',
            'atom':'iTunEXTC',
            'print':'Rating Score',
            'type':int,
            'display':False,
        },
        {
            'name':'rating annotation',
            'keyword':'rating_annotation',
            'atom':'iTunEXTC',
            'subler':'Rating Annotation',
            'print':'Rating Annotation',
            'type':unicode,
            'display':False,
        },
        {
            'name':'track #',
            'atom':'trkn',
            'subler':'Track #',
            'print':'Track',
            'type':unicode,
        },
        {
            'name':'disk #',
            'atom':'disk',
            'subler':'Disk #',
            'print':'Disk',
            'type':unicode,
        },
        {
            'name':'track position',
            'atom':'trkn',
            'mediainfo':'Track_Position',
            'print':'Track Position',
            'type':int,
            'display':False,
        },
        {
            'name':'track total',
            'atom':'trkn',
            'mediainfo':'Track_Position_Total',
            'print':'Track Total',
            'type':int,
            'display':False
        },
        {
            'name':'disk position',
            'atom':'disk',
            'mediainfo':'Part_Position',
            'print':'Disk Position',
            'type':int,
            'display':False,
        },
        {
            'name':'disk total',
            'atom':'disk',
            'mediainfo':'Part_Position_Total',
            'print':'Disk Total',
            'type':int,
            'display':False,
        },
        {
            'name':'cover',
            'atom':'covr',
            'mediainfo':'Cover',
            'print':'Cover Pieces',
            'type':int,
            'auto cast':False,
        },
    ),
    'track':{
        'common':(
            {
                'name':'enabled',
                'print':'Enabled',
                'type':bool,
            },
            {
                'name':'type',
                'print':'Type',
                'type':unicode,
            },
            {
                'name':'track id',
                'print':'Track ID',
                'mediainfo':'ID',
                'type':int,
            },
            {
                'name':'position',
                'print':'Position',
                'mediainfo':'StreamKindID',
                'type':int,
            },
            {
                'name':'format',
                'print':'Format',
                'mediainfo':'Format',
                'type':unicode,
            },
            {
                'name':'codec profile',
                'print':'Codec Profile',
                'mediainfo':'Format_Profile',
                'type':unicode,
                'plural':'list',
                'plural format':'mediainfo value list',
            },
            {
                'name':'duration',
                'print':'Duration',
                'mediainfo':'Duration',
                'type':int,
                'format':'millisecond',
            },
            {
                'name':'bit rate',
                'print':'Bit Rate',
                'mediainfo':'BitRate',
                'type':int,
                'format':'bitrate',
            },
            {
                'name':'bit rate mode',
                'print':'Bit Rate Mode',
                'mediainfo':'BitRate_Mode',
                'type':unicode,
            },
            {
                'name':'bit depth',
                'print':'Bit Depth',
                'mediainfo':'BitDepth',
                'type':int,
                'format':'bit',
            },
            {
                'name':'stream size',
                'print':'Stream Size',
                'mediainfo':'StreamSize',
                'type':int,
                'format':'byte',
            },
            {
                'name':'language',
                'print':'Language',
                'mediainfo':'Language_String3',
                'type':unicode,
            },
            {
                'name':'encoded date',
                'print':'Encoded Date',
                'mediainfo':'Encoded_Date',
                'type':'date',
                'display':False,
            },
            {
                'name':'name',
                'print':'Name',
                'mediainfo':'Title',
                'type':unicode,
            },
            {
                'name':'delay',
                'print':'Delay',
                'mediainfo':'Delay',
                'type':int,
            },
        ),
        'audio':(
            {
                'name':'channel configuration',
                'print':'Channel configuration',
                'mediainfo':'Channel_s_',
                'type':int,
                'plural':'list',
                'plural format':'mediainfo value list',
            },
            {
                'name':'channels',
                'print':'Channels',
                'type':int,
            },
            {
                'name':'channel position',
                'print':'Channel Position',
                'mediainfo':'ChannelPositions',
                'type':unicode,
                'plural':'list',
                'plural format':'mediainfo value list',
            },
            {
                'name':'sample rate',
                'print':'Sample Rate',
                'mediainfo':'SamplingRate',
                'type':int,
                'format':'frequency',
            },
            {
                'name':'sample count',
                'print':'Sample Count',
                'mediainfo':'SamplingCount',
                'type':int,
            },
            {
                'name':'dialnorm',
                'print':'Dialnorm',
                'mediainfo':'dialnorm',
                'type':int,
            },
        ),
        'video':(
            {
                'name':'width',
                'print':'Width',
                'mediainfo':'Width',
                'type':int,
                'format':'pixel',
            },
            {
                'name':'height',
                'print':'Height',
                'mediainfo':'Height',
                'type':int,
                'format':'pixel',
            },
            {
                'name':'pixel aspect ratio',
                'print':'Pixel Aspect Ratio',
                'mediainfo':'PixelAspectRatio',
                'type':float,
            },
            {
                'name':'display aspect ratio',
                'print':'Display Aspect Ratio',
                'mediainfo':'DisplayAspectRatio',
                'type':float,
            },
            {
                'name':'frame rate mode',
                'print':'Frame Rate Mode',
                'mediainfo':'FrameRate_Mode',
                'type':unicode,
            },
            {
                'name':'frame rate',
                'print':'Frame Rate',
                'mediainfo':'FrameRate',
                'type':float,
                'format':'framerate',
            },
            {
                'name':'frame rate minimum',
                'print':'Frame Rate Minimum',
                'mediainfo':'FrameRate_Minimum',
                'type':float,
                'format':'framerate',
            },
            {
                'name':'frame rate maximum',
                'print':'Frame Rate Maximum',
                'mediainfo':'FrameRate_Maximum',
                'type':float,
                'format':'framerate',
            },
            {
                'name':'frame count',
                'print':'Frame Count',
                'mediainfo':'FrameCount',
                'type':int,
            },
            {
                'name':'color space',
                'print':'Color Space',
                'mediainfo':'ColorSpace',
                'type':unicode,
            },
            {
                'name':'bpf',
                'print':'Bits / Pixel * Frame',
                'mediainfo':'Bits-_Pixel_Frame_',
                'type':float,
            },
            {
                'name':'encoder',
                'print':'Encoder',
                'mediainfo':'Encoded_Library',
                'type':unicode,
            },
            {
                'name':'encoder settings',
                'print':'Encoder Settings',
                'mediainfo':'Encoded_Library_Settings',
                'type':unicode,
                'plural':'dict',
                'display':False,
                'plural format':'mediainfo key value list',
            },
        ),
        'text':(
        ),
        'image':(
            {
                'name':'width',
                'print':'Width',
                'mediainfo':'Width',
                'type':int,
                'format':'pixel',
            },
            {
                'name':'height',
                'print':'Height',
                'mediainfo':'Height',
                'type':int,
                'format':'pixel',
            },
        )
    },
}
