# -*- coding: utf-8 -*-

prototype = {
    'knowlege':{
        'knowlege.movie':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'synonym':['keyword'],
            'element':[
                {
                    'key':'host',
                    'name':'Host',
                    'keyword':'host',
                    'type':unicode,
                },
                {
                    'key':'movie id',
                    'name':'Movie ID',
                    'keyword':'movie_id',
                    'type':int,
                },
                {
                    'key':'imdb movie id',
                    'name':'IMDB Movie ID',
                    'keyword':'imdb_movie_id',
                    'type':unicode,
                },
            ],
        },
        'knowlege.tvshow.show':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'synonym':['keyword'],
            'element':[
                {
                    'key':'host',
                    'name':'Host',
                    'keyword':'host',
                    'type':unicode,
                },
                {
                    'key':'tv show id',
                    'name':'TV Show ID',
                    'keyword':'tv_show_id',
                    'type':int,
                },
            ],
        },
        'knowlege.tvshow.season':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'synonym':['keyword'],
            'element':[
                {
                    'key':'host',
                    'name':'Host',
                    'keyword':'host',
                    'type':unicode,
                },
                {
                    'key':'tv show id',
                    'name':'TV Show ID',
                    'keyword':'tv_show_id',
                    'type':int,
                },
                {
                    'key':'tv season',
                    'name':'TV Season',
                    'keyword':'tv_season',
                    'type':int,
                },
            ],
        },
        'knowlege.tvshow.episode':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'synonym':['keyword'],
            'element':[
                {
                    'key':'host',
                    'name':'Host',
                    'keyword':'host',
                    'type':unicode,
                },
                {
                    'key':'tv show id',
                    'name':'TV Show ID',
                    'keyword':'tv_show_id',
                    'type':int,
                },
                {
                    'key':'tv season',
                    'name':'TV Season',
                    'keyword':'tv_season',
                    'type':int,
                },
                {
                    'key':'tv episode',
                    'name':'TV Episode',
                    'keyword':'tv_episode',
                    'type':int,
                },
            ],
        },
        'knowlege.person':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'synonym':['keyword'],
            'element':[
                {
                    'key':'host',
                    'name':'Host',
                    'keyword':'host',
                    'type':unicode,
                },
                {
                    'key':'person id',
                    'name':'Person ID',
                    'keyword':'person_id',
                    'type':int,
                },
            ],
        },
        'knowlege.network':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'synonym':['keyword'],
            'element':[
                {
                    'key':'host',
                    'name':'Host',
                    'keyword':'host',
                    'type':unicode,
                },
                {
                    'key':'network id',
                    'name':'Network ID',
                    'keyword':'network_id',
                    'type':int,
                },
            ],
        },
        'knowlege.studio':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'synonym':['keyword'],
            'element':[
                {
                    'key':'host',
                    'name':'Host',
                    'keyword':'host',
                    'type':unicode,
                },
                {
                    'key':'studio id',
                    'name':'Studio ID',
                    'keyword':'studio_id',
                    'type':int,
                },
            ],
        },
        'knowlege.job':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'synonym':['keyword'],
            'element':[
                {
                    'key':'host',
                    'name':'Host',
                    'keyword':'host',
                    'type':unicode,
                },
                {
                    'key':'job id',
                    'name':'Job ID',
                    'keyword':'job_id',
                    'type':int,
                },
            ],
        },
        'knowlege.department':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'synonym':['keyword'],
            'element':[
                {
                    'key':'host',
                    'name':'Host',
                    'keyword':'host',
                    'type':unicode,
                },
                {
                    'key':'department id',
                    'name':'Department ID',
                    'keyword':'department_id',
                    'type':int,
                },
            ],
        },
        'knowlege.genre':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'synonym':['keyword'],
            'element':[
                {
                    'key':'host',
                    'name':'Host',
                    'keyword':'host',
                    'type':unicode,
                },
                {
                    'key':'genre id',
                    'name':'Genre ID',
                    'keyword':'genre_id',
                    'type':int,
                },
            ],
        },
    },
    'crawl':{
        'file':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'mediainfo':None,
                'atom':None,
            },
            'synonym':['mediainfo'],
            'element':[
                {
                    'key':'character encoding',
                    'name':'Character encoding',
                    'type':unicode,
                },
                {
                    'key':'file path',
                    'name':'File path',
                    'type':unicode,
                },
                {
                    'key':'directory',
                    'name':'Directory',
                    'type':unicode,
                },
                {
                    'key':'file name',
                    'name':'File name',
                    'type':unicode,
                },
                {
                    'key':'kind',
                    'name':'Kind',
                    'type':unicode,
                },
                {
                    'key':'format',
                    'name':'Format',
                    'mediainfo':'Format',
                    'type':unicode,
                },
                {
                    'key':'size',
                    'name':'Size',
                    'mediainfo':'FileSize',
                    'type':int,
                    'format':'byte',
                },
            ],
        },
        'tag':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'mediainfo':None,
                'mp4info':None,
                'subler':None,
                'atom':None,
                'keyword':None,
            },
            'synonym':['mediainfo', 'mp4info', 'keyword'],
            'element':[
                {
                    'key':'kind',
                    'keyword':'kind',
                    'name':'Kind',
                    'type':unicode,
                },
                {
                    'key':'language',
                    'name':'Language',
                    'mediainfo':'Language_String3',
                    'type':'enum',
                    'enumeration':'language',
                },
                {
                    'key':'profile',
                    'name':'Profile',
                    'type':unicode
                },
                {
                    'key':'volume',
                    'name':'Volume',
                    'type':unicode
                },
                {
                    'key':'media kind',
                    'atom':'stik',
                    'mediainfo':'stik',
                    'subler':'Media Kind',
                    'name':'Media Kind',
                    'type':'enum',
                    'enumeration':'media kind',
                },
                {
                    'key':'name',
                    'atom':'©nam',
                    'mediainfo':'Title',
                    'subler':'Name',
                    'name':'Name',
                    'type':unicode,
                },
                {
                    'key':'artist',
                    'atom':'@ART',
                    'mediainfo':'Performer',
                    'subler':'Artist',
                    'name':'Artist',
                    'type':unicode,
                },
                {
                    'key':'album artist',
                    'atom':'aART',
                    'mediainfo':'Album_Performer',
                    'subler':'Album Artist',
                    'name':'Album Artist',
                    'type':unicode,
                },
                {
                    'key':'album',
                    'atom':'©alb',
                    'mediainfo':'Album',
                    'subler':'Album',
                    'name':'Album',
                    'type':unicode,
                },
                {
                    'key':'track #',
                    'atom':'trkn',
                    'subler':'Track #',
                    'name':'Track',
                    'type':unicode,
                },
                {
                    'key':'disk #',
                    'atom':'disk',
                    'subler':'Disk #',
                    'name':'Disk',
                    'type':unicode,
                },
                {
                    'key':'track position',
                    'atom':'trkn',
                    'mediainfo':'Track_Position',
                    'name':'Track Position',
                    'type':int,
                },
                {
                    'key':'track total',
                    'atom':'trkn',
                    'mediainfo':'Track_Position_Total',
                    'name':'Track Total',
                    'type':int,
                },
                {
                    'key':'disk position',
                    'atom':'disk',
                    'mediainfo':'Part_Position',
                    'name':'Disk Position',
                    'type':int,
                },
                {
                    'key':'disk total',
                    'atom':'disk',
                    'mediainfo':'Part_Position_Total',
                    'name':'Disk Total',
                    'type':int,
                },
                {
                    'key':'tv show',
                    'atom':'tvsh',
                    'mediainfo':'tvsh',
                    'subler':'TV Show',
                    'name':'TV Show',
                    'type':unicode,
                },
                {
                    'key':'tv episode id',
                    'atom':'tven',
                    'mediainfo':'tven',
                    'subler':'TV Episode ID',
                    'name':'TV Episode ID',
                    'type':unicode,
                },
                {
                    'key':'tv season',
                    'keyword':'tv_season',
                    'atom':'tvsn',
                    'mediainfo':'tvsn',
                    'subler':'TV Season',
                    'name':'TV Season',
                    'type':int,
                },
                {
                    'key':'tv episode',
                    'keyword':'tv_episode',
                    'atom':'tves',
                    'mediainfo':'tves',
                    'subler':'TV Episode #',
                    'name':'TV Episode',
                    'type':int,
                },
                {
                    'key':'tv network',
                    'atom':'tvnn',
                    'mediainfo':'tvnn',
                    'subler':'TV Network',
                    'name':'TV Network',
                    'type':unicode,
                },
                {
                    'key':'grouping',
                    'atom':'©grp',
                    'mediainfo':'Grouping',
                    'subler':'Grouping',
                    'name':'Grouping',
                    'type':unicode,
                },
                {
                    'key':'composer',
                    'atom':'©wrt',
                    'mediainfo':'ScreenplayBy',
                    'subler':'Composer',
                    'name':'Composer',
                    'type':unicode,
                },
                {
                    'key':'comment',
                    'atom':'©cmt',
                    'mediainfo':'Comment',
                    'subler':'Comments',
                    'name':'Comment',
                    'type':unicode,
                },
                {
                    'key':'sort name',
                    'keyword':'sort_name',
                    'atom':'sonm',
                    'mediainfo':'sonm',
                    'subler':'Sort Name',
                    'name':'Sort Name',
                    'type':unicode,
                },
                {
                    'key':'sort artist',
                    'keyword':'sort_artist',
                    'atom':'soar',
                    'mediainfo':'soar',
                    'subler':'Sort Artist',
                    'name':'Sort Artist',
                    'type':unicode,
                },
                {
                    'key':'sort album artist',
                    'keyword':'sort_album_artist',
                    'atom':'soaa',
                    'mediainfo':'soaa',
                    'subler':'Sort Album Artist',
                    'name':'Sort Album Artist',
                    'type':unicode,
                },
                {
                    'key':'sort album',
                    'keyword':'sort_album',
                    'atom':'soal',
                    'mediainfo':'soal',
                    'subler':'Sort Album',
                    'name':'Sort Album',
                    'type':unicode,
                },
                {
                    'key':'sort composer',
                    'keyword':'sort_composer',
                    'atom':'soco',
                    'mediainfo':'soco',
                    'subler':'Sort Composer',
                    'name':'Sort Composer',
                    'type':unicode,
                },
                {
                    'key':'sort tv show',
                    'keyword':'sort_tv_show',
                    'atom':'sosn',
                    'mediainfo':'sosn',
                    'subler':'Sort TV Show',
                    'name':'Sort TV Show',
                    'type':unicode,
                },
                {
                    'key':'description',
                    'atom':'desc',
                    'mediainfo':'desc',
                    'subler':'Description',
                    'name':'Description',
                    'type':unicode,
                    'unescape xml':True,
                },
                {
                    'key':'long description',
                    'atom':'ldes',
                    'mediainfo':'ldes',
                    'subler':'Long Description',
                    'name':'Long Description',
                    'type':unicode,
                    'unescape xml':True,
                },
                {
                    'key':'lyrics',
                    'atom':'©lyr',
                    'mp4info':'Lyrics',
                    'subler':'Lyrics',
                    'name':'Lyrics',
                    'type':unicode,
                    'unescape xml':True,
                },
                {
                    'key':'copyright',
                    'atom':'cprt',
                    'mediainfo':'Copyright',
                    'subler':'Copyright',
                    'name':'Copyright',
                    'type':unicode,
                },
                {
                    # mediainfo seems to mix @enc and @too into Encoded_Application
                    'key':'encoding tool',
                    'atom':'©too',
                    'mp4info':'Encoded with',
                    'subler':'Encoding Tool',
                    'name':'Encoding Tool',
                    'type':unicode,
                },
                {
                    'key':'encoded by',
                    'atom':'@enc',
                    'mediainfo':None, # mediainfo seems to mix @enc and @too into Encoded_Application
                    'mp4info':'Encoded by',
                    'subler':'Encoded by',
                    'name':'Encoded by',
                    'type':unicode,
                },
                {
                    'key':'release date',
                    'atom':'©day',
                    'mediainfo':'Recorded_Date',
                    'subler':'Release Date',
                    'name':'Release Date',
                    'type':'date',
                },
                {
                    'key':'compilation',
                    'atom':'cpil',
                    'mediainfo':'Compilation',
                    'name':'Compilation',
                    'type':bool
                },
                {
                    'key':'tempo',
                    'atom':'tmpo',
                    'mediainfo':'BPM',
                    'subler':'Tempo',
                    'name':'Tempo',
                    'type':int,
                },
                {
                    'key':'genre type',
                    'atom':'gnre',
                    'mp4info':'GenreType',
                    'name':'Genre Type',
                    'type':'enum',
                    'enumeration':'genre',
                },
                {
                    'key':'genre',
                    'atom':'©gen',
                    'mp4info':'Genre',
                    'subler':'Genre',
                    'name':'Genre',
                    'type':unicode,
                },
                {
                    'key':'hd video',
                    'atom':'hdvd',
                    'mediainfo':'hdvd',
                    'subler':'HD Video',
                    'name':'HD Video',
                    'type':bool
                },
                {
                    'key':'gapless',
                    'atom':'pgap',
                    'mp4info':'Part of Gapless Album',
                    'subler':'Gapless',
                    'name':'Gapless',
                    'type':bool
                },
                {
                    'key':'podcast',
                    'atom':'pcst',
                    'mediainfo':'pcst',
                    'name':'Podcast',
                    'type':bool
                },
                {
                    'key':'podcast url',
                    'atom':'purl',
                    'name':'Podcast URL',
                    'type':unicode,
                },
                {
                    'key':'keywords',
                    'atom':'keyw',
                    'mediainfo':'keyw',
                    'name':'Keywords',
                    'type':unicode,
                },
                {
                    'key':'category',
                    'atom':'catg',
                    'mediainfo':'catg',
                    'name':'Category',
                    'type':unicode,
                },
                {
                    'key':'xid',
                    'atom':'xid',
                    'mediainfo':'xid',
                    'subler':'XID',
                    'name':'XID',
                    'type':unicode,
                },
                {
                    'key':'itunes content id',
                    'atom':'cnID',
                    'mediainfo':'cnID',
                    'subler':'contentID',
                    'name':'iTunes content ID',
                    'type':int,
                },
                {
                    'key':'itunes account',
                    'atom':'apID',
                    'mediainfo':'apID',
                    'subler':'iTunes Account',
                    'name':'iTunes account ID',
                    'type':unicode,
                },
                {
                    'key':'itunes artist id',
                    'atom':'atID',
                    'mediainfo':'atID',
                    'name':'iTunes artist ID',
                    'type':int,
                },
                {
                    'key':'itunes composer id',
                    'atom':'cmID',
                    'mediainfo':'cmID',
                    'name':'iTunes composer ID',
                    'type':int,
                },
                {
                    'key':'itunes playlist id',
                    'atom':'plID',
                    'mediainfo':'plID',
                    'name':'iTunes playlist ID',
                    'type':int,
                },
                {
                    'key':'itunes genre id',
                    'atom':'geID',
                    'mediainfo':'geID',
                    'name':'iTunes genre ID',
                    'type':int,
                },
                {
                    'key':'itunes country id',
                    'atom':'sfID',
                    'mediainfo':'sfID',
                    'name':'iTunes country ID',
                    'type':'enum',
                    'enumeration':'country',
                },
                {
                    'key':'itunes account type',
                    'atom':'akID',
                    'mediainfo':'akID',
                    'name':'iTunes account type',
                    'type':'enum',
                    'enumeration':'itunes account type',
                },
                {
                    'key':'episode global id',
                    'atom':'egid',
                    'name':'Episode Global ID',
                    'type':int,
                },
                {
                    'key':'purchase date',
                    'atom':'purd',
                    'mediainfo':'purd',
                    'subler':'Purchase Date',
                    'name':'Purchase Date',
                    'type':'date',
                },
                {
                    'key':'content rating',
                    'atom':'rtng',
                    'mediainfo':'rtng',
                    'subler':'Content Rating',
                    'name':'Content Rating',
                    'type':'enum',
                    'enumeration':'content rating',
                },
                {
                    'key':'itunextc',
                    'atom':'iTunEXTC',
                    'mediainfo':'iTunEXTC',
                    'name':'iTunEXTC',
                    'type':unicode,
                },
                {
                    'key':'itunmovi',
                    'atom':'iTunMOVI',
                    'mediainfo':'iTunMOVI',
                    'name':'iTunMOVI',
                    'type':'plist',
                },
                {
                    'key':'cast',
                    'atom':'iTunMOVI',
                    'subler':'Cast',
                    'name':'Cast',
                    'type':unicode,
                    'plural':'list',
                },
                {
                    'key':'directors',
                    'atom':'iTunMOVI',
                    'subler':'Director',
                    'name':'Directors',
                    'type':unicode,
                    'plural':'list',
                },
                {
                    'key':'codirectors',
                    'atom':'iTunMOVI',
                    'subler':'Codirectors',
                    'name':'Codirectors',
                    'type':unicode,
                    'plural':'list',
                },
                {
                    'key':'producers',
                    'atom':'iTunMOVI',
                    'subler':'Producers',
                    'name':'Producers',
                    'type':unicode,
                    'plural':'list',
                },
                {
                    'key':'screenwriters',
                    'atom':'iTunMOVI',
                    'subler':'Screenwriters',
                    'name':'Screenwriters',
                    'type':unicode,
                    'plural':'list',
                },
                {
                    'key':'studio',
                    'atom':'iTunMOVI',
                    'subler':'Studio',
                    'name':'Studio',
                    'type':unicode,
                    'plural':'list',
                },
                {
                    'key':'rating standard',
                    'keyword':'rating_standard',
                    'atom':'iTunEXTC',
                    'name':'Rating Standard',
                    'type':unicode,
                },
                {
                    'key':'rating',
                    'keyword':'rating',
                    'atom':'iTunEXTC',
                    'subler':'Rating',
                    'name':'Rating',
                    'type':unicode,
                },
                {
                    'key':'rating score',
                    'keyword':'rating_score',
                    'atom':'iTunEXTC',
                    'name':'Rating Score',
                    'type':int,
                },
                {
                    'key':'rating annotation',
                    'keyword':'rating_annotation',
                    'atom':'iTunEXTC',
                    'subler':'Rating Annotation',
                    'name':'Rating Annotation',
                    'type':unicode,
                },
                {
                    'key':'cover',
                    'atom':'covr',
                    'mediainfo':'Cover',
                    'name':'Cover Pieces',
                    'type':int,
                    'auto cast':False,
                },
                {
                    'key':'modified date',
                    'name':'Modified Date',
                    'mediainfo':'File_Modified_Date',
                    'type':'date',
                },
                {
                    'key':'tag date',
                    'name':'Tag Date',
                    'mediainfo':'Tagged_Date',
                    'type':'date',
                },
                {
                    'key':'bit rate',
                    'name':'Bit Rate',
                    'mediainfo':'OverallBitRate',
                    'type':int,
                    'format':'bitrate',
                },
                {
                    'key':'duration',
                    'name':'Duration',
                    'mediainfo':'Duration',
                    'type':int,
                    'format':'millisecond',
                },
                {
                    'key':'width',
                    'name':'Width',
                    'mediainfo':'Width',
                    'type':int,
                    'format':'pixel',
                },
                {
                    'key':'height',
                    'name':'Height',
                    'mediainfo':'Height',
                    'type':int,
                    'format':'pixel',
                },
                {
                    'key':'imdb id',
                    'keyword':'imdb_id',
                    'name':'IMDb',
                    'type':unicode
                },
                {
                    'key':'tv show key',
                    'keyword':'tv_show_key',
                    'name':'TV Show Key',
                    'type':unicode,
                },
                {
                    'key':'simple name',
                    'keyword':'simple_name',
                    'name':'Simple Name',
                    'type':unicode,
                },
            ],
        }
    },
    'track':{
        'audio':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'mediainfo':None,
                'atom':None,
            },
            'synonym':['mediainfo'],
            'element':[
                {
                    'key':'name',
                    'name':'Name',
                    'mediainfo':'Title',
                    'type':unicode,
                },
                {
                    'key':'language',
                    'name':'Language',
                    'mediainfo':'Language_String3',
                    'type':'enum',
                    'enumeration':'language',
                },
                {
                    'key':'track id',
                    'name':'Track ID',
                    'mediainfo':'ID',
                    'type':int,
                },
                {
                    'key':'type',
                    'name':'Type',
                    'type':unicode,
                },
                {
                    'key':'delay',
                    'name':'Delay',
                    'mediainfo':'Delay',
                    'type':int,
                },
                {
                    'key':'position',
                    'name':'Position',
                    'mediainfo':'StreamKindID',
                    'type':int,
                },
                {
                    'key':'format',
                    'name':'Format',
                    'mediainfo':'Format',
                    'type':unicode,
                },
                {
                    'key':'codec profile',
                    'name':'Codec Profile',
                    'mediainfo':'Format_Profile',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'mediainfo value list',
                },
                {
                    'key':'duration',
                    'name':'Duration',
                    'mediainfo':'Duration',
                    'type':int,
                    'format':'millisecond',
                },
                {
                    'key':'bit rate',
                    'name':'Bit Rate',
                    'mediainfo':'BitRate',
                    'type':int,
                    'format':'bitrate',
                },
                {
                    'key':'bit rate mode',
                    'name':'Bit Rate Mode',
                    'mediainfo':'BitRate_Mode',
                    'type':unicode,
                },
                {
                    'key':'bit depth',
                    'name':'Bit Depth',
                    'mediainfo':'BitDepth',
                    'type':int,
                    'format':'bit',
                },
                {
                    'key':'stream size',
                    'name':'Stream Size',
                    'mediainfo':'StreamSize',
                    'type':int,
                    'format':'byte',
                },
                {
                    'key':'encoded date',
                    'name':'Encoded Date',
                    'mediainfo':'Encoded_Date',
                    'type':'date',
                },
                {
                    'key':'channel configuration',
                    'name':'Channel configuration',
                    'mediainfo':'Channel_s_',
                    'type':int,
                    'plural':'list',
                    'plural format':'mediainfo value list',
                },
                {
                    'key':'channels',
                    'name':'Channels',
                    'type':int,
                },
                {
                    'key':'channel position',
                    'name':'Channel Position',
                    'mediainfo':'ChannelPositions',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'mediainfo value list',
                },
                {
                    'key':'sample rate',
                    'name':'Sample Rate',
                    'mediainfo':'SamplingRate',
                    'type':int,
                    'format':'frequency',
                },
                {
                    'key':'sample count',
                    'name':'Sample Count',
                    'mediainfo':'SamplingCount',
                    'type':int,
                },
                {
                    'key':'dialnorm',
                    'name':'Dialnorm',
                    'mediainfo':'dialnorm',
                    'type':int,
                },
            ],
        },
        'video':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'mediainfo':None,
                'atom':None,
            },
            'synonym':['mediainfo'],
            'element':[
                {
                    'key':'name',
                    'name':'Name',
                    'mediainfo':'Title',
                    'type':unicode,
                },
                {
                    'key':'language',
                    'name':'Language',
                    'mediainfo':'Language_String3',
                    'type':'enum',
                    'enumeration':'language',
                },
                {
                    'key':'track id',
                    'name':'Track ID',
                    'mediainfo':'ID',
                    'type':int,
                },
                {
                    'key':'type',
                    'name':'Type',
                    'type':unicode,
                },
                {
                    'key':'delay',
                    'name':'Delay',
                    'mediainfo':'Delay',
                    'type':int,
                },
                {
                    'key':'position',
                    'name':'Position',
                    'mediainfo':'StreamKindID',
                    'type':int,
                },
                {
                    'key':'format',
                    'name':'Format',
                    'mediainfo':'Format',
                    'type':unicode,
                },
                {
                    'key':'codec profile',
                    'name':'Codec Profile',
                    'mediainfo':'Format_Profile',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'mediainfo value list',
                },
                {
                    'key':'duration',
                    'name':'Duration',
                    'mediainfo':'Duration',
                    'type':int,
                    'format':'millisecond',
                },
                {
                    'key':'bit rate',
                    'name':'Bit Rate',
                    'mediainfo':'BitRate',
                    'type':int,
                    'format':'bitrate',
                },
                {
                    'key':'bit rate mode',
                    'name':'Bit Rate Mode',
                    'mediainfo':'BitRate_Mode',
                    'type':unicode,
                },
                {
                    'key':'bit depth',
                    'name':'Bit Depth',
                    'mediainfo':'BitDepth',
                    'type':int,
                    'format':'bit',
                },
                {
                    'key':'stream size',
                    'name':'Stream Size',
                    'mediainfo':'StreamSize',
                    'type':int,
                    'format':'byte',
                },
                {
                    'key':'encoded date',
                    'name':'Encoded Date',
                    'mediainfo':'Encoded_Date',
                    'type':'date',
                },
                {
                    'key':'width',
                    'name':'Width',
                    'mediainfo':'Width',
                    'type':int,
                    'format':'pixel',
                },
                {
                    'key':'height',
                    'name':'Height',
                    'mediainfo':'Height',
                    'type':int,
                    'format':'pixel',
                },
                {
                    'key':'pixel aspect ratio',
                    'name':'Pixel Aspect Ratio',
                    'mediainfo':'PixelAspectRatio',
                    'type':float,
                },
                {
                    'key':'display aspect ratio',
                    'name':'Display Aspect Ratio',
                    'mediainfo':'DisplayAspectRatio',
                    'type':float,
                },
                {
                    'key':'frame rate mode',
                    'name':'Frame Rate Mode',
                    'mediainfo':'FrameRate_Mode',
                    'type':unicode,
                },
                {
                    'key':'frame rate',
                    'name':'Frame Rate',
                    'mediainfo':'FrameRate',
                    'type':float,
                    'format':'framerate',
                },
                {
                    'key':'frame rate minimum',
                    'name':'Frame Rate Minimum',
                    'mediainfo':'FrameRate_Minimum',
                    'type':float,
                    'format':'framerate',
                },
                {
                    'key':'frame rate maximum',
                    'name':'Frame Rate Maximum',
                    'mediainfo':'FrameRate_Maximum',
                    'type':float,
                    'format':'framerate',
                },
                {
                    'key':'frame count',
                    'name':'Frame Count',
                    'mediainfo':'FrameCount',
                    'type':int,
                },
                {
                    'key':'color space',
                    'name':'Color Space',
                    'mediainfo':'ColorSpace',
                    'type':unicode,
                },
                {
                    'key':'bpf',
                    'name':'Bits / Pixel * Frame',
                    'mediainfo':'Bits-_Pixel_Frame_',
                    'type':float,
                },
                {
                    'key':'encoder',
                    'name':'Encoder',
                    'mediainfo':'Encoded_Library',
                    'type':unicode,
                },
                {
                    'key':'encoder settings',
                    'name':'Encoder Settings',
                    'mediainfo':'Encoded_Library_Settings',
                    'type':unicode,
                    'plural':'dict',
                    'plural format':'mediainfo key value list',
                },
            ],
        },
        'text':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'mediainfo':None,
                'atom':None,
            },
            'synonym':['mediainfo'],
            'element':[
                {
                    'key':'name',
                    'name':'Name',
                    'mediainfo':'Title',
                    'type':unicode,
                },
                {
                    'key':'language',
                    'name':'Language',
                    'mediainfo':'Language_String3',
                    'type':'enum',
                    'enumeration':'language',
                },
                {
                    'key':'track id',
                    'name':'Track ID',
                    'mediainfo':'ID',
                    'type':int,
                },
                {
                    'key':'type',
                    'name':'Type',
                    'type':unicode,
                },
                {
                    'key':'delay',
                    'name':'Delay',
                    'mediainfo':'Delay',
                    'type':int,
                },
                {
                    'key':'position',
                    'name':'Position',
                    'mediainfo':'StreamKindID',
                    'type':int,
                },
                {
                    'key':'format',
                    'name':'Format',
                    'mediainfo':'Format',
                    'type':unicode,
                },
                {
                    'key':'codec profile',
                    'name':'Codec Profile',
                    'mediainfo':'Format_Profile',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'mediainfo value list',
                },
                {
                    'key':'duration',
                    'name':'Duration',
                    'mediainfo':'Duration',
                    'type':int,
                    'format':'millisecond',
                },
                {
                    'key':'bit rate',
                    'name':'Bit Rate',
                    'mediainfo':'BitRate',
                    'type':int,
                    'format':'bitrate',
                },
                {
                    'key':'bit rate mode',
                    'name':'Bit Rate Mode',
                    'mediainfo':'BitRate_Mode',
                    'type':unicode,
                },
                {
                    'key':'bit depth',
                    'name':'Bit Depth',
                    'mediainfo':'BitDepth',
                    'type':int,
                    'format':'bit',
                },
                {
                    'key':'stream size',
                    'name':'Stream Size',
                    'mediainfo':'StreamSize',
                    'type':int,
                    'format':'byte',
                },
                {
                    'key':'encoded date',
                    'name':'Encoded Date',
                    'mediainfo':'Encoded_Date',
                    'type':'date',
                },
            ],
        },
        'image':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'mediainfo':None,
                'atom':None,
            },
            'synonym':['mediainfo'],
            'element':[
                {
                    'key':'name',
                    'name':'Name',
                    'mediainfo':'Title',
                    'type':unicode,
                },
                {
                    'key':'language',
                    'name':'Language',
                    'mediainfo':'Language_String3',
                    'type':'enum',
                    'enumeration':'language',
                },
                {
                    'key':'track id',
                    'name':'Track ID',
                    'mediainfo':'ID',
                    'type':int,
                },
                {
                    'key':'type',
                    'name':'Type',
                    'type':unicode,
                },
                {
                    'key':'delay',
                    'name':'Delay',
                    'mediainfo':'Delay',
                    'type':int,
                },
                {
                    'key':'position',
                    'name':'Position',
                    'mediainfo':'StreamKindID',
                    'type':int,
                },
                {
                    'key':'format',
                    'name':'Format',
                    'mediainfo':'Format',
                    'type':unicode,
                },
                {
                    'key':'codec profile',
                    'name':'Codec Profile',
                    'mediainfo':'Format_Profile',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'mediainfo value list',
                },
                {
                    'key':'duration',
                    'name':'Duration',
                    'mediainfo':'Duration',
                    'type':int,
                    'format':'millisecond',
                },
                {
                    'key':'bit rate',
                    'name':'Bit Rate',
                    'mediainfo':'BitRate',
                    'type':int,
                    'format':'bitrate',
                },
                {
                    'key':'bit rate mode',
                    'name':'Bit Rate Mode',
                    'mediainfo':'BitRate_Mode',
                    'type':unicode,
                },
                {
                    'key':'bit depth',
                    'name':'Bit Depth',
                    'mediainfo':'BitDepth',
                    'type':int,
                    'format':'bit',
                },
                {
                    'key':'stream size',
                    'name':'Stream Size',
                    'mediainfo':'StreamSize',
                    'type':int,
                    'format':'byte',
                },
                {
                    'key':'encoded date',
                    'name':'Encoded Date',
                    'mediainfo':'Encoded_Date',
                    'type':'date',
                },
                {
                    'key':'width',
                    'name':'Width',
                    'mediainfo':'Width',
                    'type':int,
                    'format':'pixel',
                },
                {
                    'key':'height',
                    'name':'Height',
                    'mediainfo':'Height',
                    'type':int,
                    'format':'pixel',
                },
            ],
        }
    },
    'tmdb':{
        #'tmdb.movie.cast':{},
        #'tmdb.movie.poster':{},
        #'tmdb.movie.keyword':{},
        #'tmdb.movie.release':{},
        #'tmdb.movie.trailer':{},
        #'tmdb.movie.translation':{},
        #'tmdb.movie.alternative':{},
        #'tmdb.person.poster':{},
        #'tmdb.person.credit':{},
        'tmdb.movie':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
                'tmdb':None,
            },
            'synonym':['keyword'],
            'element':[
                {
                    'key':'tmdb movie id',
                    'name':'TMDB movie ID',
                    'keyword':'tmdb_movie_id',
                    'tmdb':'id',
                    'type':int,
                },
                {
                    'key':'imdb movie id',
                    'name':'IMDB movie ID',
                    'keyword':'imdb_movie_id',
                    'tmdb':'imdb_id',
                    'type':unicode,
                },
                {
                    'key':'language',
                    'name':'Language',
                    'keyword':'language',
                    'type':'enum',
                    'enumeration':'language',
                },
            ],
        },
        'tmdb.person':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'synonym':['keyword'],
            'element':[
                {
                    'key':'tmdb person id',
                    'name':'TMDB person ID',
                    'keyword':'tmdb_person_id',
                    'type':int,
                },
            ],
        },
    },
    'tvdb':{
        'tvdb.show.cast':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'tvdb':None,
                'keyword':None,
            },
            'tag':'Actor',
            'coalesce':True,
            'synonym':['tvdb', 'keyword'],
            'element':[
                {
                    'key':'tvdb tv show id',
                    'name':'TVDB TV Show ID',
                    'keyword':'tvdb_tv_show_id',
                    'type':int,
                },
                {
                    'key':'tvdb person id',
                    'name':'TVDB Person ID',
                    'keyword':'tvdb_person_id',
                    'tvdb':'id',
                    'type':int,
                },
                {
                    'key':'image url',
                    'name':'Image URL',
                    'tvdb':'Image',
                    'type':unicode,
                },
                {
                    'key':'name',
                    'name':'Name',
                    'tvdb':'Name',
                    'type':unicode,
                },
                {
                    'key':'character',
                    'name':'Character',
                    'tvdb':'Role',
                    'type':unicode,
                },
                {
                    'key':'sort order',
                    'name':'Sort Order',
                    'tvdb':'SortOrder',
                    'type':int,
                },
            ],
        },
        'tvdb.show.poster':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'tvdb':None,
                'keyword':None,
            },
            'tag':'Banner',
            'coalesce':True,
            'synonym':['tvdb', 'keyword'],
            'element':[
                {
                    'key':'tvdb tv show id',
                    'name':'TVDB TV Show ID',
                    'keyword':'tvdb_tv_show_id',
                    'type':int,
                },
                {
                    'key':'tvdb image id',
                    'name':'TVDB Image ID',
                    'tvdb':'id',
                    'type':int,
                },
                {
                    'key':'tv season',
                    'name':'TV Season',
                    'tvdb':'Season',
                    'type':int,
                },
                {
                    'key':'language',
                    'name':'Language',
                    'tvdb':'Language',
                    'type':'enum',
                    'enumeration':'language',
                },
                {
                    'key':'url',
                    'name':'URL',
                    'tvdb':'BannerPath',
                    'type':unicode,
                },
                {
                    # fanart, poster, season, series
                    'key':'tvdb image context',
                    'name':'TVDB Image Context',
                    'tvdb':'BannerType',
                    'type':unicode,
                },
                {
                    # season, seasonwide, text, graphical, blank,
                    # 1920x1080, 1280x720, 680x1000
                    'key':'tvdb image layout',
                    'name':'TVDB Image Layout',
                    'tvdb':'BannerType2',
                    'type':unicode,
                },
                {
                    'key':'user rating',
                    'name':'User Rating',
                    'tvdb':'Rating',
                    'type':float,
                },
                {
                    'key':'user rating count',
                    'name':'User Rating Count',
                    'tvdb':'RatingCount',
                    'type':int,
                },
                {
                    'key':'tv show name text',
                    'name':'TV Show Name Text',
                    'tvdb':'SeriesName',
                    'type':bool,
                },
                {
                    'tvdb':'Colors',
                    'enabled':False,
                },
                {
                    'tvdb':'ThumbnailPath',
                    'enabled':False,
                },
                {
                    'tvdb':'VignettePath',
                    'enabled':False,
                },
            ],
        },
        'tvdb.show':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'tvdb':None,
                'keyword':None,
            },
            'tag':'Series',
            'coalesce':False,
            'synonym':['tvdb', 'keyword'],
            'element':[
                {
                    'key':'tvdb tv show id',
                    'name':'TVDB TV Show ID',
                    'keyword':'tvdb_tv_show_id',
                    'tvdb':'id',
                    'type':int,
                },
                {
                    'key':'imdb id',
                    'name':'IMDB ID',
                    'tvdb':'IMDB_ID',
                    'type':unicode,
                },
                {
                    'key':'zap2it id',
                    'name':'Zap2It ID',
                    'tvdb':'zap2it_id',
                    'type':unicode,
                },
                {
                    'key':'name',
                    'name':'Name',
                    'tvdb':'SeriesName',
                    'type':unicode,
                },
                {
                    'key':'modified',
                    'name':'Modified',
                    'tvdb':'lastupdated',
                    'type':int,
                },
                {
                    'key':'release date',
                    'name':'Release Date',
                    'tvdb':'FirstAired',
                    'type':'date',
                },
                {
                    'key':'rating',
                    'name':'Rating',
                    'tvdb':'ContentRating',
                    'type':unicode,
                },
                {
                    'key':'language',
                    'name':'Language',
                    'keyword':'language',
                    'tvdb':'Language',
                    'type':'enum',
                    'enumeration':'language',
                },
                {
                    'key':'overview',
                    'name':'Overview',
                    'tvdb':'Overview',
                    'type':unicode,
                },
                {
                    'key':'user rating',
                    'name':'User Rating',
                    'tvdb':'Rating',
                    'type':float,
                },
                {
                    'key':'user rating count',
                    'name':'User Rating Count',
                    'tvdb':'RatingCount',
                    'type':int,
                },
                {
                    'key':'runtime',
                    'name':'Runtime',
                    'tvdb':'Runtime',
                    'type':int,
                },
                {
                    'key':'status',
                    'name':'Status',
                    'tvdb':'Status',
                    'type':unicode,
                },
                {
                    'key':'tv network',
                    'name':'TV Network',
                    'tvdb':'Network',
                    'type':unicode,
                },
                {
                    'key':'genre',
                    'name':'Genre',
                    'tvdb':'Genre',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'tvdb list',
                },
                {
                    'key':'actor',
                    'name':'Actor',
                    'tvdb':'Actors',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'tvdb list',
                },
                {
                    'key':'poster url',
                    'name':'Poster URL',
                    'tvdb':'poster',
                    'type':unicode,
                },
                {
                    'key':'banner url',
                    'name':'Banner URL',
                    'tvdb':'banner',
                    'type':unicode,
                },
                {
                    'key':'fan art url',
                    'name':'Fan Art URL',
                    'tvdb':'fanart',
                    'type':unicode,
                },
                {
                    'tvdb':'SeriesID',
                    'type':int,
                    'enabled':False,
                },
                {
                    'tvdb':'NetworkID',
                    'enabled':False,
                },
                {
                    'tvdb':'added',
                    'enabled':False,
                },
                {
                    'tvdb':'addedBy',
                    'enabled':False,
                },
                {
                    'tvdb':'Airs_DayOfWeek',
                    'type':unicode,
                    'enabled':False,
                },
                {
                    'tvdb':'Airs_Time',
                    'type':'time',
                    'enabled':False,
                },
            ],
        },
        'tvdb.episode':{
            'default':{
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'tvdb':None,
                'keyword':None,
            },
            'tag':'Episode',
            'coalesce':False,
            'synonym':['tvdb', 'keyword'],
            'element':[
                {
                    'key':'tvdb tv show id',
                    'name':'TVDB TV Show ID',
                    'keyword':'tvdb_tv_show_id',
                    'tvdb':'seriesid',
                    'type':int,
                },
                {
                    'key':'tvdb tv season id',
                    'name':'TVDB TV Season ID',
                    'tvdb':'seasonid',
                    'type':int,
                },
                {
                    'key':'tvdb tv episode id',
                    'name':'TVDB TV Episode ID',
                    'keyword':'tvdb_tv_episode_id',
                    'tvdb':'id',
                    'type':int,
                },
                {
                    'key':'tv season',
                    'name':'TV Season',
                    'keyword':'tv_season',
                    'tvdb':'SeasonNumber',
                    'type':int,
                },
                {
                    'key':'tv episode',
                    'name':'TV Episode',
                    'keyword':'tv_episode',
                    'tvdb':'EpisodeNumber',
                    'type':int,
                },
                {
                    'key':'name',
                    'name':'Name',
                    'tvdb':'EpisodeName',
                    'type':unicode,
                },
                {
                    'key':'absolute tv episode',
                    'name':'Absolute TV Episode',
                    'tvdb':'absolute_number',
                    'type':int,
                },
                {
                    'key':'imdb id',
                    'name':'IMDB ID',
                    'tvdb':'IMDB_ID',
                    'type':unicode,
                },
                {
                    'key':'modified',
                    'name':'Modified',
                    'tvdb':'lastupdated',
                    'type':int,
                },
                {
                    'key':'language',
                    'name':'Language',
                    'keyword':'language',
                    'tvdb':'Language',
                    'type':'enum',
                    'enumeration':'language',
                },
                {
                    'key':'release date',
                    'name':'Release Date',
                    'tvdb':'FirstAired',
                    'type':'date',
                },
                {
                    'key':'overview',
                    'name':'Overview',
                    'tvdb':'Overview',
                    'type':unicode
                },
                {
                    'key':'production code',
                    'name':'Production Code',
                    'tvdb':'ProductionCode',
                    'type':unicode,
                },
                {
                    'key':'user rating',
                    'name':'User Rating',
                    'tvdb':'Rating',
                    'type':float,
                },
                {
                    'key':'user rating count',
                    'name':'User Rating Count',
                    'tvdb':'RatingCount',
                    'type':int,
                },
                {
                    'key':'poster url',
                    'name':'Poster URL',
                    'tvdb':'filename',
                    'type':unicode,
                },
                {
                    'key':'actor',
                    'name':'Actor',
                    'tvdb':'GuestStars',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'tvdb list',
                },
                {
                    'key':'director',
                    'name':'Director',
                    'tvdb':'Director',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'tvdb list',
                },
                {
                    'key':'screenwriter',
                    'name':'Screenwriter',
                    'tvdb':'Writer',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'tvdb list',
                },
                {
                    'tvdb':'Combined_episodenumber',
                    'enabled':False,
                },
                {
                    'tvdb':'Combined_season',
                    'enabled':False,
                },
                {
                    'tvdb':'DVD_chapter',
                    'enabled':False,
                },
                {
                    'tvdb':'DVD_discid',
                    'enabled':False,
                },
                {
                    'tvdb':'DVD_episodenumber',
                    'enabled':False,
                },
                {
                    'tvdb':'DVD_season',
                    'enabled':False,
                },
                {
                    'tvdb':'EpImgFlag',
                    'enabled':False,
                },
            ],
        },
    },
}
