# -*- coding: utf-8 -*-

prototype = {
    'knowlege':{
        'knowlege.movie':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'index':['name', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'movie id',
                    'keyword':'movie_id',
                    'type':int,
                },
                {
                    'name':'imdb movie id',
                    'keyword':'imdb_movie_id',
                    'type':unicode,
                },
            ],
        },
        'knowlege.tvshow.show':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'index':['name', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'tv show id',
                    'keyword':'tv_show_id',
                    'type':int,
                },
            ],
        },
        'knowlege.tvshow.season':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'index':['name', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'tv show id',
                    'keyword':'tv_show_id',
                    'type':int,
                },
                {
                    'name':'tv season',
                    'keyword':'tv_season',
                    'type':int,
                },
            ],
        },
        'knowlege.tvshow.episode':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'index':['name', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'tv show id',
                    'keyword':'tv_show_id',
                    'type':int,
                },
                {
                    'name':'tv season',
                    'keyword':'tv_season',
                    'type':int,
                },
                {
                    'name':'tv episode',
                    'keyword':'tv_episode',
                    'type':int,
                },
            ],
        },
        'knowlege.person':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'index':['name', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'person id',
                    'keyword':'person_id',
                    'type':int,
                },
            ],
        },
        'knowlege.network':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'index':['name', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'network id',
                    'keyword':'network_id',
                    'type':int,
                },
            ],
        },
        'knowlege.studio':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'index':['name', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'studio id',
                    'keyword':'studio_id',
                    'type':int,
                },
            ],
        },
        'knowlege.job':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'index':['name', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'job id',
                    'keyword':'job_id',
                    'type':int,
                },
            ],
        },
        'knowlege.department':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'index':['name', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'department id',
                    'keyword':'department_id',
                    'type':int,
                },
            ],
        },
        'knowlege.genre':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'index':['name', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'genre id',
                    'keyword':'genre_id',
                    'type':int,
                },
            ],
        },
    },
    'crawl':{
        'file':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'mediainfo':None,
                'atom':None,
            },
            'index':['name', 'mediainfo'],
            'element':[
                {
                    'name':'character encoding',
                    'print':'Character encoding',
                    'type':unicode,
                },
                {
                    'name':'file path',
                    'print':'File path',
                    'type':unicode,
                },
                {
                    'name':'directory',
                    'print':'Directory',
                    'type':unicode,
                },
                {
                    'name':'file name',
                    'print':'File name',
                    'type':unicode,
                },
                {
                    'name':'kind',
                    'print':'Kind',
                    'type':unicode,
                },
                {
                    'name':'format',
                    'print':'Format',
                    'mediainfo':'Format',
                    'type':unicode,
                },
                {
                    'name':'size',
                    'print':'Size',
                    'mediainfo':'FileSize',
                    'type':int,
                    'format':'byte',
                },
            ],
        },
        'tag':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'mediainfo':None,
                'mp4info':None,
                'subler':None,
                'atom':None,
                'keyword':None,
            },
            'index':['name', 'mediainfo', 'mp4info', 'subler', 'keyword'],
            'element':[
                {
                    'name':'enabled',
                    'print':'Enabled',
                    'type':bool,
                },
                {
                    'name':'kind',
                    'keyword':'kind',
                    'print':'Kind',
                    'type':unicode,
                },
                {
                    'name':'language',
                    'print':'Language',
                    'mediainfo':'Language_String3',
                    'type':'enum',
                },
                {
                    'name':'profile',
                    'print':'Profile',
                    'type':unicode
                },
                {
                    'name':'volume',
                    'print':'Volume',
                    'type':unicode
                },
                {
                    'name':'media kind',
                    'atom':'stik',
                    'mediainfo':'stik',
                    'subler':'Media Kind',
                    'print':'Media Kind',
                    'type':'enum',
                    'enumeration':'stik',
                },
                {
                    'name':'name',
                    'atom':'©nam',
                    'mediainfo':'Title',
                    'subler':'Name',
                    'print':'Name',
                    'type':unicode,
                },
                {
                    'name':'artist',
                    'atom':'@ART',
                    'mediainfo':'Performer',
                    'subler':'Artist',
                    'print':'Artist',
                    'type':unicode,
                },
                {
                    'name':'album artist',
                    'atom':'aART',
                    'mediainfo':'Album_Performer',
                    'subler':'Album Artist',
                    'print':'Album Artist',
                    'type':unicode,
                },
                {
                    'name':'album',
                    'atom':'©alb',
                    'mediainfo':'Album',
                    'subler':'Album',
                    'print':'Album',
                    'type':unicode,
                },
                {
                    'name':'track #',
                    'atom':'trkn',
                    'subler':'Track #',
                    'print':'Track',
                    'type':unicode,
                },
                {
                    'name':'disk #',
                    'atom':'disk',
                    'subler':'Disk #',
                    'print':'Disk',
                    'type':unicode,
                },
                {
                    'name':'track position',
                    'atom':'trkn',
                    'mediainfo':'Track_Position',
                    'print':'Track Position',
                    'type':int,
                },
                {
                    'name':'track total',
                    'atom':'trkn',
                    'mediainfo':'Track_Position_Total',
                    'print':'Track Total',
                    'type':int,
                },
                {
                    'name':'disk position',
                    'atom':'disk',
                    'mediainfo':'Part_Position',
                    'print':'Disk Position',
                    'type':int,
                },
                {
                    'name':'disk total',
                    'atom':'disk',
                    'mediainfo':'Part_Position_Total',
                    'print':'Disk Total',
                    'type':int,
                },
                {
                    'name':'tv show',
                    'atom':'tvsh',
                    'mediainfo':'tvsh',
                    'subler':'TV Show',
                    'print':'TV Show',
                    'type':unicode,
                },
                {
                    'name':'tv episode id',
                    'atom':'tven',
                    'mediainfo':'tven',
                    'subler':'TV Episode ID',
                    'print':'TV Episode ID',
                    'type':unicode,
                },
                {
                    'name':'tv season',
                    'keyword':'tv_season',
                    'atom':'tvsn',
                    'mediainfo':'tvsn',
                    'subler':'TV Season',
                    'print':'TV Season',
                    'type':int,
                },
                {
                    'name':'tv episode',
                    'keyword':'tv_episode',
                    'atom':'tves',
                    'mediainfo':'tves',
                    'subler':'TV Episode #',
                    'print':'TV Episode',
                    'type':int,
                },
                {
                    'name':'tv network',
                    'atom':'tvnn',
                    'mediainfo':'tvnn',
                    'subler':'TV Network',
                    'print':'TV Network',
                    'type':unicode,
                },
                {
                    'name':'grouping',
                    'atom':'©grp',
                    'mediainfo':'Grouping',
                    'subler':'Grouping',
                    'print':'Grouping',
                    'type':unicode,
                },
                {
                    'name':'composer',
                    'atom':'©wrt',
                    'mediainfo':'ScreenplayBy',
                    'subler':'Composer',
                    'print':'Composer',
                    'type':unicode,
                },
                {
                    'name':'comment',
                    'atom':'©cmt',
                    'mediainfo':'Comment',
                    'subler':'Comments',
                    'print':'Comment',
                    'type':unicode,
                },
                {
                    'name':'sort name',
                    'keyword':'sort_name',
                    'atom':'sonm',
                    'mediainfo':'sonm',
                    'subler':'Sort Name',
                    'print':'Sort Name',
                    'type':unicode,
                },
                {
                    'name':'sort artist',
                    'keyword':'sort_artist',
                    'atom':'soar',
                    'mediainfo':'soar',
                    'subler':'Sort Artist',
                    'print':'Sort Artist',
                    'type':unicode,
                },
                {
                    'name':'sort album artist',
                    'keyword':'sort_album_artist',
                    'atom':'soaa',
                    'mediainfo':'soaa',
                    'subler':'Sort Album Artist',
                    'print':'Sort Album Artist',
                    'type':unicode,
                },
                {
                    'name':'sort album',
                    'keyword':'sort_album',
                    'atom':'soal',
                    'mediainfo':'soal',
                    'subler':'Sort Album',
                    'print':'Sort Album',
                    'type':unicode,
                },
                {
                    'name':'sort composer',
                    'keyword':'sort_composer',
                    'atom':'soco',
                    'mediainfo':'soco',
                    'subler':'Sort Composer',
                    'print':'Sort Composer',
                    'type':unicode,
                },
                {
                    'name':'sort tv show',
                    'keyword':'sort_tv_show',
                    'atom':'sosn',
                    'mediainfo':'sosn',
                    'subler':'Sort TV Show',
                    'print':'Sort TV Show',
                    'type':unicode,
                },
                {
                    'name':'description',
                    'atom':'desc',
                    'mediainfo':'desc',
                    'subler':'Description',
                    'print':'Description',
                    'type':unicode,
                    'unescape xml':True,
                },
                {
                    'name':'long description',
                    'atom':'ldes',
                    'mediainfo':'ldes',
                    'subler':'Long Description',
                    'print':'Long Description',
                    'type':unicode,
                    'unescape xml':True,
                },
                {
                    'name':'lyrics',
                    'atom':'©lyr',
                    'mp4info': 'Lyrics',
                    'subler':'Lyrics',
                    'print':'Lyrics',
                    'type':unicode,
                    'unescape xml':True,
                },
                {
                    'name':'copyright',
                    'atom':'cprt',
                    'mediainfo':'Copyright',
                    'subler':'Copyright',
                    'print':'Copyright',
                    'type':unicode,
                },
                {
                    # mediainfo seems to mix @enc and @too into Encoded_Application
                    'name':'encoding tool',
                    'atom':'©too',
                    'mp4info': 'Encoded with',
                    'subler':'Encoding Tool',
                    'print':'Encoding Tool',
                    'type':unicode,
                },
                {
                    'name':'encoded by',
                    'atom':'@enc',
                    'mediainfo':None, # mediainfo seems to mix @enc and @too into Encoded_Application
                    'mp4info': 'Encoded by',
                    'subler':'Encoded by',
                    'print':'Encoded by',
                    'type':unicode,
                },
                {
                    'name':'release date',
                    'atom':'©day',
                    'mediainfo':'Recorded_Date',
                    'subler':'Release Date',
                    'print':'Release Date',
                    'type':'date',
                },
                {
                    'name':'compilation',
                    'atom':'cpil',
                    'mediainfo':'Compilation',
                    'print':'Compilation',
                    'type':bool
                },
                {
                    'name':'tempo',
                    'atom':'tmpo',
                    'mediainfo':'BPM',
                    'subler':'Tempo',
                    'print':'Tempo',
                    'type':int,
                },
                {
                    'name':'genre type',
                    'atom':'gnre',
                    'mp4info':'GenreType',
                    'print':'Genre Type',
                    'type':'enum',
                    'enumeration':'gnre',
                },
                {
                    'name':'genre',
                    'atom':'©gen',
                    'mp4info': 'Genre',
                    'subler':'Genre',
                    'print':'Genre',
                    'type':unicode,
                },
                {
                    'name':'hd video',
                    'atom':'hdvd',
                    'mediainfo':'hdvd',
                    'subler':'HD Video',
                    'print':'HD Video',
                    'type':bool
                },
                {
                    'name':'gapless',
                    'atom':'pgap',
                    'mp4info': 'Part of Gapless Album',
                    'subler':'Gapless',
                    'print':'Gapless',
                    'type':bool
                },
                {
                    'name':'podcast',
                    'atom':'pcst',
                    'mediainfo':'pcst',
                    'print':'Podcast',
                    'type':bool
                },
                {
                    'name':'podcast url',
                    'atom':'purl',
                    'print':'Podcast URL',
                    'type':unicode,
                },
                {
                    'name':'keywords',
                    'atom':'keyw',
                    'mediainfo':'keyw',
                    'print':'Keywords',
                    'type':unicode,
                },
                {
                    'name':'category',
                    'atom':'catg',
                    'mediainfo':'catg',
                    'print':'Category',
                    'type':unicode,
                },
                {
                    'name':'xid',
                    'atom':'xid',
                    'mediainfo':'xid',
                    'subler':'XID',
                    'print':'XID',
                    'type':unicode,
                },
                {
                    'name':'itunes content id',
                    'atom':'cnID',
                    'mediainfo':'cnID',
                    'subler':'contentID',
                    'print':'iTunes content ID',
                    'type':int,
                },
                {
                    'name':'itunes account',
                    'atom':'apID',
                    'mediainfo':'apID',
                    'subler':'iTunes Account',
                    'print':'iTunes account ID',
                    'type':unicode,
                },
                {
                    'name':'itunes artist id',
                    'atom':'atID',
                    'mediainfo':'atID',
                    'print':'iTunes artist ID',
                    'type':int,
                },
                {
                    'name':'itunes composer id',
                    'atom':'cmID',
                    'mediainfo':'cmID',
                    'print':'iTunes composer ID',
                    'type':int,
                },
                {
                    'name':'itunes playlist id',
                    'atom':'plID',
                    'mediainfo':'plID',
                    'print':'iTunes playlist ID',
                    'type':int,
                },
                {
                    'name':'itunes genre id',
                    'atom':'geID',
                    'mediainfo':'geID',
                    'print':'iTunes genre ID',
                    'type':int,
                },
                {
                    'name':'itunes country id',
                    'atom':'sfID',
                    'mediainfo':'sfID',
                    'print':'iTunes country ID',
                    'type':'enum',
                    'enumeration':'sfID',
                },
                {
                    'name':'itunes account type',
                    'atom':'akID',
                    'mediainfo':'akID',
                    'print':'iTunes account type',
                    'type':'enum',
                    'enumeration':'akID',
                },
                {
                    'name':'episode global id',
                    'atom':'egid',
                    'print':'Episode Global ID',
                    'type':int,
                },
                {
                    'name':'purchase date',
                    'atom':'purd',
                    'mediainfo':'purd',
                    'subler':'Purchase Date',
                    'print':'Purchase Date',
                    'type':'date',
                },
                {
                    'name':'content rating',
                    'atom':'rtng',
                    'mediainfo':'rtng',
                    'subler':'Content Rating',
                    'print':'Content Rating',
                    'type':'enum',
                    'enumeration':'rtng',
                },
                {
                    'name':'itunextc',
                    'atom':'iTunEXTC',
                    'mediainfo':'iTunEXTC',
                    'print':'iTunEXTC',
                    'type':unicode,
                },
                {
                    'name':'itunmovi',
                    'atom':'iTunMOVI',
                    'mediainfo':'iTunMOVI',
                    'print':'iTunMOVI',
                    'type':'plist',
                },
                {
                    'name':'cast',
                    'atom':'iTunMOVI',
                    'subler':'Cast',
                    'print':'Cast',
                    'type':unicode,
                    'plural':'list',
                },
                {
                    'name':'directors',
                    'atom':'iTunMOVI',
                    'subler':'Director',
                    'print':'Directors',
                    'type':unicode,
                    'plural':'list',
                },
                {
                    'name':'codirectors',
                    'atom':'iTunMOVI',
                    'subler':'Codirectors',
                    'print':'Codirectors',
                    'type':unicode,
                    'plural':'list',
                },
                {
                    'name':'producers',
                    'atom':'iTunMOVI',
                    'subler':'Producers',
                    'print':'Producers',
                    'type':unicode,
                    'plural':'list',
                },
                {
                    'name':'screenwriters',
                    'atom':'iTunMOVI',
                    'subler':'Screenwriters',
                    'print':'Screenwriters',
                    'type':unicode,
                    'plural':'list',
                },
                {
                    'name':'studio',
                    'atom':'iTunMOVI',
                    'subler':'Studio',
                    'print':'Studio',
                    'type':unicode,
                    'plural':'list',
                },
                {
                    'name':'rating standard',
                    'keyword':'rating_standard',
                    'atom':'iTunEXTC',
                    'print':'Rating Standard',
                    'type':unicode,
                },
                {
                    'name':'rating',
                    'keyword':'rating',
                    'atom':'iTunEXTC',
                    'subler':'Rating',
                    'print':'Rating',
                    'type':unicode,
                },
                {
                    'name':'rating score',
                    'keyword':'rating_score',
                    'atom':'iTunEXTC',
                    'print':'Rating Score',
                    'type':int,
                },
                {
                    'name':'rating annotation',
                    'keyword':'rating_annotation',
                    'atom':'iTunEXTC',
                    'subler':'Rating Annotation',
                    'print':'Rating Annotation',
                    'type':unicode,
                },
                {
                    'name':'cover',
                    'atom':'covr',
                    'mediainfo':'Cover',
                    'print':'Cover Pieces',
                    'type':int,
                    'auto cast':False,
                },
                {
                    'name':'modified date',
                    'print':'Modified Date',
                    'mediainfo':'File_Modified_Date',
                    'type':'date',
                },
                {
                    'name':'tag date',
                    'print':'Tag Date',
                    'mediainfo':'Tagged_Date',
                    'type':'date',
                },
                {
                    'name':'bit rate',
                    'print':'Bit Rate',
                    'mediainfo':'OverallBitRate',
                    'type':int,
                    'format':'bitrate',
                },
                {
                    'name':'duration',
                    'print':'Duration',
                    'mediainfo':'Duration',
                    'type':int,
                    'format':'millisecond',
                },
                {
                    'name':'width',
                    'print':'Width',
                    'mediainfo':'Width',
                    'type':int,
                    'format':'pixel',
                },
                {
                    'name':'height',
                    'print':'Height',
                    'mediainfo':'Height',
                    'type':int,
                    'format':'pixel',
                },
                {
                    'name':'imdb id',
                    'keyword':'imdb_id',
                    'print':'IMDb',
                    'type':unicode
                },
                {
                    'name':'tv show key',
                    'keyword':'tv_show_key',
                    'print':'TV Show Key',
                    'type':unicode,
                },
                {
                    'name':'simple name',
                    'keyword':'simple_name',
                    'print':'Simple Name',
                    'type':unicode,
                },
            ],
        }
    },
    'track':{
        'audio':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'mediainfo':None,
                'atom':None,
            },
            'index':['name', 'mediainfo'],
            'element':[
                {
                    'name':'enabled',
                    'print':'Enabled',
                    'type':bool,
                },
                {
                    'name':'name',
                    'print':'Name',
                    'mediainfo':'Title',
                    'type':unicode,
                },
                {
                    'name':'language',
                    'print':'Language',
                    'mediainfo':'Language_String3',
                    'type':'enum',
                },
                {
                    'name':'track id',
                    'print':'Track ID',
                    'mediainfo':'ID',
                    'type':int,
                },
                {
                    'name':'type',
                    'print':'Type',
                    'type':unicode,
                },
                {
                    'name':'delay',
                    'print':'Delay',
                    'mediainfo':'Delay',
                    'type':int,
                },
                {
                    'name':'position',
                    'print':'Position',
                    'mediainfo':'StreamKindID',
                    'type':int,
                },
                {
                    'name':'format',
                    'print':'Format',
                    'mediainfo':'Format',
                    'type':unicode,
                },
                {
                    'name':'codec profile',
                    'print':'Codec Profile',
                    'mediainfo':'Format_Profile',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'mediainfo value list',
                },
                {
                    'name':'duration',
                    'print':'Duration',
                    'mediainfo':'Duration',
                    'type':int,
                    'format':'millisecond',
                },
                {
                    'name':'bit rate',
                    'print':'Bit Rate',
                    'mediainfo':'BitRate',
                    'type':int,
                    'format':'bitrate',
                },
                {
                    'name':'bit rate mode',
                    'print':'Bit Rate Mode',
                    'mediainfo':'BitRate_Mode',
                    'type':unicode,
                },
                {
                    'name':'bit depth',
                    'print':'Bit Depth',
                    'mediainfo':'BitDepth',
                    'type':int,
                    'format':'bit',
                },
                {
                    'name':'stream size',
                    'print':'Stream Size',
                    'mediainfo':'StreamSize',
                    'type':int,
                    'format':'byte',
                },
                {
                    'name':'encoded date',
                    'print':'Encoded Date',
                    'mediainfo':'Encoded_Date',
                    'type':'date',
                },
                {
                    'name':'channel configuration',
                    'print':'Channel configuration',
                    'mediainfo':'Channel_s_',
                    'type':int,
                    'plural':'list',
                    'plural format':'mediainfo value list',
                },
                {
                    'name':'channels',
                    'print':'Channels',
                    'type':int,
                },
                {
                    'name':'channel position',
                    'print':'Channel Position',
                    'mediainfo':'ChannelPositions',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'mediainfo value list',
                },
                {
                    'name':'sample rate',
                    'print':'Sample Rate',
                    'mediainfo':'SamplingRate',
                    'type':int,
                    'format':'frequency',
                },
                {
                    'name':'sample count',
                    'print':'Sample Count',
                    'mediainfo':'SamplingCount',
                    'type':int,
                },
                {
                    'name':'dialnorm',
                    'print':'Dialnorm',
                    'mediainfo':'dialnorm',
                    'type':int,
                },
            ],
        },
        'video':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'mediainfo':None,
                'atom':None,
            },
            'index':['name', 'mediainfo'],
            'element':[
                {
                    'name':'enabled',
                    'print':'Enabled',
                    'type':bool,
                },
                {
                    'name':'name',
                    'print':'Name',
                    'mediainfo':'Title',
                    'type':unicode,
                },
                {
                    'name':'language',
                    'print':'Language',
                    'mediainfo':'Language_String3',
                    'type':'enum',
                },
                {
                    'name':'track id',
                    'print':'Track ID',
                    'mediainfo':'ID',
                    'type':int,
                },
                {
                    'name':'type',
                    'print':'Type',
                    'type':unicode,
                },
                {
                    'name':'delay',
                    'print':'Delay',
                    'mediainfo':'Delay',
                    'type':int,
                },
                {
                    'name':'position',
                    'print':'Position',
                    'mediainfo':'StreamKindID',
                    'type':int,
                },
                {
                    'name':'format',
                    'print':'Format',
                    'mediainfo':'Format',
                    'type':unicode,
                },
                {
                    'name':'codec profile',
                    'print':'Codec Profile',
                    'mediainfo':'Format_Profile',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'mediainfo value list',
                },
                {
                    'name':'duration',
                    'print':'Duration',
                    'mediainfo':'Duration',
                    'type':int,
                    'format':'millisecond',
                },
                {
                    'name':'bit rate',
                    'print':'Bit Rate',
                    'mediainfo':'BitRate',
                    'type':int,
                    'format':'bitrate',
                },
                {
                    'name':'bit rate mode',
                    'print':'Bit Rate Mode',
                    'mediainfo':'BitRate_Mode',
                    'type':unicode,
                },
                {
                    'name':'bit depth',
                    'print':'Bit Depth',
                    'mediainfo':'BitDepth',
                    'type':int,
                    'format':'bit',
                },
                {
                    'name':'stream size',
                    'print':'Stream Size',
                    'mediainfo':'StreamSize',
                    'type':int,
                    'format':'byte',
                },
                {
                    'name':'encoded date',
                    'print':'Encoded Date',
                    'mediainfo':'Encoded_Date',
                    'type':'date',
                },
                {
                    'name':'width',
                    'print':'Width',
                    'mediainfo':'Width',
                    'type':int,
                    'format':'pixel',
                },
                {
                    'name':'height',
                    'print':'Height',
                    'mediainfo':'Height',
                    'type':int,
                    'format':'pixel',
                },
                {
                    'name':'pixel aspect ratio',
                    'print':'Pixel Aspect Ratio',
                    'mediainfo':'PixelAspectRatio',
                    'type':float,
                },
                {
                    'name':'display aspect ratio',
                    'print':'Display Aspect Ratio',
                    'mediainfo':'DisplayAspectRatio',
                    'type':float,
                },
                {
                    'name':'frame rate mode',
                    'print':'Frame Rate Mode',
                    'mediainfo':'FrameRate_Mode',
                    'type':unicode,
                },
                {
                    'name':'frame rate',
                    'print':'Frame Rate',
                    'mediainfo':'FrameRate',
                    'type':float,
                    'format':'framerate',
                },
                {
                    'name':'frame rate minimum',
                    'print':'Frame Rate Minimum',
                    'mediainfo':'FrameRate_Minimum',
                    'type':float,
                    'format':'framerate',
                },
                {
                    'name':'frame rate maximum',
                    'print':'Frame Rate Maximum',
                    'mediainfo':'FrameRate_Maximum',
                    'type':float,
                    'format':'framerate',
                },
                {
                    'name':'frame count',
                    'print':'Frame Count',
                    'mediainfo':'FrameCount',
                    'type':int,
                },
                {
                    'name':'color space',
                    'print':'Color Space',
                    'mediainfo':'ColorSpace',
                    'type':unicode,
                },
                {
                    'name':'bpf',
                    'print':'Bits / Pixel * Frame',
                    'mediainfo':'Bits-_Pixel_Frame_',
                    'type':float,
                },
                {
                    'name':'encoder',
                    'print':'Encoder',
                    'mediainfo':'Encoded_Library',
                    'type':unicode,
                },
                {
                    'name':'encoder settings',
                    'print':'Encoder Settings',
                    'mediainfo':'Encoded_Library_Settings',
                    'type':unicode,
                    'plural':'dict',
                    'plural format':'mediainfo key value list',
                },
            ],
        },
        'text':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'mediainfo':None,
                'atom':None,
            },
            'index':['name', 'mediainfo'],
            'element':[
                {
                    'name':'enabled',
                    'print':'Enabled',
                    'type':bool,
                },
                {
                    'name':'name',
                    'print':'Name',
                    'mediainfo':'Title',
                    'type':unicode,
                },
                {
                    'name':'language',
                    'print':'Language',
                    'mediainfo':'Language_String3',
                    'type':'enum',
                },
                {
                    'name':'track id',
                    'print':'Track ID',
                    'mediainfo':'ID',
                    'type':int,
                },
                {
                    'name':'type',
                    'print':'Type',
                    'type':unicode,
                },
                {
                    'name':'delay',
                    'print':'Delay',
                    'mediainfo':'Delay',
                    'type':int,
                },
                {
                    'name':'position',
                    'print':'Position',
                    'mediainfo':'StreamKindID',
                    'type':int,
                },
                {
                    'name':'format',
                    'print':'Format',
                    'mediainfo':'Format',
                    'type':unicode,
                },
                {
                    'name':'codec profile',
                    'print':'Codec Profile',
                    'mediainfo':'Format_Profile',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'mediainfo value list',
                },
                {
                    'name':'duration',
                    'print':'Duration',
                    'mediainfo':'Duration',
                    'type':int,
                    'format':'millisecond',
                },
                {
                    'name':'bit rate',
                    'print':'Bit Rate',
                    'mediainfo':'BitRate',
                    'type':int,
                    'format':'bitrate',
                },
                {
                    'name':'bit rate mode',
                    'print':'Bit Rate Mode',
                    'mediainfo':'BitRate_Mode',
                    'type':unicode,
                },
                {
                    'name':'bit depth',
                    'print':'Bit Depth',
                    'mediainfo':'BitDepth',
                    'type':int,
                    'format':'bit',
                },
                {
                    'name':'stream size',
                    'print':'Stream Size',
                    'mediainfo':'StreamSize',
                    'type':int,
                    'format':'byte',
                },
                {
                    'name':'encoded date',
                    'print':'Encoded Date',
                    'mediainfo':'Encoded_Date',
                    'type':'date',
                },
            ],
        },
        'image':{
            'index':['name', 'mediainfo'],
            'element':[
                {
                    'name':'enabled',
                    'print':'Enabled',
                    'type':bool,
                },
                {
                    'name':'name',
                    'print':'Name',
                    'mediainfo':'Title',
                    'type':unicode,
                },
                {
                    'name':'language',
                    'print':'Language',
                    'mediainfo':'Language_String3',
                    'type':'enum',
                },
                {
                    'name':'track id',
                    'print':'Track ID',
                    'mediainfo':'ID',
                    'type':int,
                },
                {
                    'name':'type',
                    'print':'Type',
                    'type':unicode,
                },
                {
                    'name':'delay',
                    'print':'Delay',
                    'mediainfo':'Delay',
                    'type':int,
                },
                {
                    'name':'position',
                    'print':'Position',
                    'mediainfo':'StreamKindID',
                    'type':int,
                },
                {
                    'name':'format',
                    'print':'Format',
                    'mediainfo':'Format',
                    'type':unicode,
                },
                {
                    'name':'codec profile',
                    'print':'Codec Profile',
                    'mediainfo':'Format_Profile',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'mediainfo value list',
                },
                {
                    'name':'duration',
                    'print':'Duration',
                    'mediainfo':'Duration',
                    'type':int,
                    'format':'millisecond',
                },
                {
                    'name':'bit rate',
                    'print':'Bit Rate',
                    'mediainfo':'BitRate',
                    'type':int,
                    'format':'bitrate',
                },
                {
                    'name':'bit rate mode',
                    'print':'Bit Rate Mode',
                    'mediainfo':'BitRate_Mode',
                    'type':unicode,
                },
                {
                    'name':'bit depth',
                    'print':'Bit Depth',
                    'mediainfo':'BitDepth',
                    'type':int,
                    'format':'bit',
                },
                {
                    'name':'stream size',
                    'print':'Stream Size',
                    'mediainfo':'StreamSize',
                    'type':int,
                    'format':'byte',
                },
                {
                    'name':'encoded date',
                    'print':'Encoded Date',
                    'mediainfo':'Encoded_Date',
                    'type':'date',
                },
                {
                    'name':'width',
                    'print':'Width',
                    'mediainfo':'Width',
                    'type':int,
                    'format':'pixel',
                },
                {
                    'name':'height',
                    'print':'Height',
                    'mediainfo':'Height',
                    'type':int,
                    'format':'pixel',
                },
            ],
        }
    },
    'tmdb':{
        'tmdb.movie':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'index':['name', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'tmdb movie id',
                    'keyword':'tmdb_movie_id'
                    'type':int,
                },
                {
                    'name':'language',
                    'tvdb':'Language',
                    'type':'enum',
                },
            ],
        },
        'tmdb.person':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'index':['name', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'tmdb person id',
                    'keyword':'tmdb_person_id'
                    'type':int,
                },
            ],
        },
    },
    'tvdb':{
        'tvdb.show.cast':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'tvdb':None,
                'keyword':None,
            },
            'tag':'Actor',
            'coalesce':True,
            'index':['name', 'tvdb', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'tvdb tv show id',
                    'keyword':'tvdb_tv_show_id'
                    'type':int,
                },
                {
                    'name':'tvdb person id',
                    'keyword':'tvdb_person_id',
                    'tvdb':'id',
                    'type':int,
                },
                {
                    'name':'image url',
                    'tvdb':'Image',
                    'type':unicode,
                },
                {
                    'name':'name',
                    'tvdb':'Name',
                    'type':unicode,
                },
                {
                    'name':'character',
                    'tvdb':'Role',
                    'type':unicode,
                },
                {
                    'name':'sort order',
                    'tvdb':'SortOrder',
                    'type':int,
                },
            ],
        },
        'tvdb.show.poster':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'tag':'Banner',
            'coalesce':True,
            'index':['name', 'tvdb', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'tvdb tv show id',
                    'keyword':'tvdb_tv_show_id'
                    'type':int,
                },
                {
                    'name':'tvdb image id',
                    'name':'tvdb_image_id',
                    'tvdb':'id',
                    'type':int,
                },
                {
                    'name':'tv season',
                    'tvdb':'Season',
                    'type':int,
                },
                {
                    'name':'language',
                    'tvdb':'Language',
                    'type':'enum',
                },
                {
                    'name':'url',
                    'tvdb':'BannerPath',
                    'type':unicode,
                },
                {
                    # fanart, poster, season, series
                    'name':'tvdb image context',
                    'tvdb':'BannerType',
                    'type':unicode,
                },
                {
                    # season, seasonwide, text, graphical, blank,
                    # 1920x1080, 1280x720, 680x1000
                    'name':'tvdb image layout',
                    'tvdb':'BannerType2',
                    'type':unicode,
                },
                {
                    'name':'user rating',
                    'tvdb':'Rating',
                    'type':float,
                },
                {
                    'name':'user rating count',
                    'tvdb':'RatingCount',
                    'type':int,
                },
                {
                    'name':'tv show name text',
                    'tvdb':'SeriesName',
                    'type':bool,
                },
                {
                    'tvdb':'Colors',
                    'enable':False,
                },
                {
                    'tvdb':'ThumbnailPath',
                    'enable':False,
                },
                {
                    'tvdb':'VignettePath',
                    'enable':False,
                },
            ],
        },
        'tvdb.show':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'tag':'Series',
            'coalesce':False,
            'index':['name', 'tvdb', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'tvdb tv show id',
                    'keyword':'tvdb_tv_show_id'
                    'tvdb':'id',
                    'type':int,
                },
                {
                    'name':'imdb id',
                    'tvdb':'IMDB_ID',
                    'type':unicode,
                },
                {
                    'name':'zap2it id',
                    'tvdb':'zap2it_id',
                    'type':unicode,
                },
                {
                    'name':'name',
                    'tvdb':'SeriesName',
                    'type':unicode,
                },
                {
                    'name':'modified',
                    'tvdb':'lastupdated',
                    'type':'date',
                },
                {
                    'name':'release date',
                    'tvdb':'FirstAired',
                    'type':'date',
                },
                {
                    'name':'rating',
                    'tvdb':'ContentRating',
                    'type':unicode,
                },
                {
                    'name':'language',
                    'tvdb':'Language',
                    'type':'enum',
                },
                {
                    'name':'overview',
                    'tvdb':'Overview',
                    'type':unicode,
                },
                {
                    'tvdb':'Rating',
                    'name':'user rating',
                    'type':float,
                },
                {
                    'name':'user rating count',
                    'tvdb':'RatingCount',
                    'type':int,
                },
                {
                    'name':'runtime',
                    'tvdb':'Runtime',
                    'type':int,
                },
                {
                    'name':'status',
                    'tvdb':'Status',
                    'type':unicode,
                },
                {
                    'name':'tv network',
                    'tvdb':'Network',
                    'type':unicode,
                },
                {
                    'name':'genre',
                    'tvdb':'Genre',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'tvdb list',
                },
                {
                    'name':'actor',
                    'tvdb':'Actors',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'tvdb list',
                },
                {
                    'name':'poster url',
                    'tvdb':'poster',
                    'type':unicode,
                },
                {
                    'name':'banner url',
                    'tvdb':'banner',
                    'type':unicode,
                },
                {
                    'name':'fan art url',
                    'tvdb':'fanart',
                    'type':unicode,
                },
                {
                    'tvdb':'SeriesID',
                    'type':int,
                    'enable':False,
                },
                {
                    'tvdb':'NetworkID',
                    'enable':False,
                },
                {
                    'tvdb':'added',
                    'enable':False,
                },
                {
                    'tvdb':'addedBy',
                    'enable':False,
                },
                {
                    'tvdb':'Airs_DayOfWeek',
                    'type':unicode,
                    'enable':False,
                },
                {
                    'tvdb':'Airs_Time',
                    'type':'time',
                    'enable':False,
                },
            ],
        },
        'tvdb.episode':{
            'default':{
                'enabled':True,
                'auto cast':True,
                'plural':None,
                'unescape xml':False,
                'keyword':None,
            },
            'tag':'Episode',
            'coalesce':False,
            'index':['name', 'tvdb', 'keyword'],
            'element':[
                {
                    'name':'host',
                    'keyword':'host'
                    'type':unicode,
                },
                {
                    'name':'tvdb tv show id',
                    'keyword':'tvdb_tv_show_id',
                    'tvdb':'seriesid',
                    'type':int,
                },
                {
                    'name':'tvdb tv season id',
                    'tvdb':'seasonid',
                    'type':int,
                },
                {
                    'name':'tvdb tv episode id',
                    'keyword':'tvdb_tv_episode_id',
                    'tvdb':'id',
                    'type':int,
                },
                {
                    'name':'tv season',
                    'tvdb':'SeasonNumber',
                    'type':int,
                },
                {
                    'name':'tv episode',
                    'tvdb':'EpisodeNumber',
                    'type':int,
                },
                {
                    'name':'name',
                    'tvdb':'EpisodeName',
                    'type':unicode,
                },
                {
                    'name':'absolute tv episode',
                    'tvdb':'absolute_number',
                    'type':int,
                },
                {
                    'name':'imdb id',
                    'tvdb':'IMDB_ID',
                    'type':unicode,
                },
                {
                    'name':'modified',
                    'tvdb':'lastupdated',
                    'type':'date',
                },
                {
                    'name':'language',
                    'tvdb':'Language',
                    'type':'enum',
                },
                {
                    'name':'release date',
                    'tvdb':'FirstAired',
                    'type':'date',
                },
                {
                    'name':'overview',
                    'tvdb':'Overview',
                    'type':unicode
                },
                {
                    'name':'production code',
                    'tvdb':'ProductionCode',
                    'type':unicode,
                },
                {
                    'name':'user rating',
                    'tvdb':'Rating',
                    'type':float,
                },
                {
                    'name':'user rating count',
                    'tvdb':'RatingCount',
                    'type':int,
                },
                {
                    'name':'poster url',
                    'tvdb':'filename',
                    'type':unicode,
                },
                {
                    'name':'actor',
                    'tvdb':'GuestStars',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'tvdb list',
                },
                {
                    'name':'director',
                    'tvdb':'Director',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'tvdb list',
                },
                {
                    'name':'screenwriter',
                    'tvdb':'Writer',
                    'type':unicode,
                    'plural':'list',
                    'plural format':'tvdb list',
                },
                {
                    'tvdb':'Combined_episodenumber',
                    'enable':False,
                },
                {
                    'tvdb':'Combined_season',
                    'enable':False,
                },
                {
                    'tvdb':'DVD_chapter',
                    'enable':False,
                },
                {
                    'tvdb':'DVD_discid',
                    'enable':False,
                },
                {
                    'tvdb':'DVD_episodenumber',
                    'enable':False,
                },
                {
                    'tvdb':'DVD_season',
                    'enable':False,
                },
                {
                    'tvdb':'EpImgFlag',
                    'enable':False,
                },
            ],
        },
    },
}
