# -*- coding: utf-8 -*-

line_replace = list()
line_replace.append([r'\b *(,|\.|\?|%|!|\$) *\b', r'\1 '])
line_replace.append([r'\.\s*\.\s*\.\.?', r'...'])
line_replace.append([r'</?[a-z]+/?>', r''])
line_replace.append([r'\'{2}', r'"'])
line_replace.append([r'\s+\)', r')'])
line_replace.append([r'\(\s+', '('])
line_replace.append([r'\s+\]', r']'])
line_replace.append([r'\[\s+', '['])
line_replace.append([r'\[[^\]]+\]\s*', r''])
line_replace.append([r'^[^\]]+\]', r''])
line_replace.append([r'\[[^\]]+\$', r''])
line_replace.append([r'\([A-Z0-9l\s]+\)', r''])
line_replace.append([r'\([A-Z0-9l\s]+$', r''])
line_replace.append([r'^[A-Z0-9l\s]+\)', r''])
line_replace.append([r'\b[-A-Z0-9\s]+:\s*', r''])
line_replace.append([r'Theysaid', r'They said'])
line_replace.append([r'\bIast\b', r'last'])
line_replace.append([r'\bIook\b', r'look'])
line_replace.append([r'\bIetting\b', r'letting'])
line_replace.append([r'\bIet\b', r'let'])
line_replace.append([r'\bshe\'II\b', r'she\'ll'])
line_replace.append([r'\bIooking\b', r'looking'])
line_replace.append([r'\bIife\b', r'life'])
line_replace.append([r'\bIeft\b', r'left'])
line_replace.append([r'\bIike\b', r'like'])
line_replace.append([r'\bIittle\b', r'little'])
line_replace.append([r'\b(P|p)Iease\b', r'\1lease'])
line_replace.append([r'\bIadies\b', r'ladies'])
line_replace.append([r'\bIearn\b', r'learn'])
line_replace.append([r'\bIanded\b', r'landed'])
line_replace.append([r'\bIocked\b', r'locked'])
line_replace.append([r'\bIie\b', r'lie'])
line_replace.append([r'\bCIaire\b', r'Claire'])
line_replace.append([r'\bIong\b', r'long'])
line_replace.append([r'\bIine\b', r'line'])
line_replace.append([r'\byou\'II\b', r'you\'ll'])
line_replace.append([r'\bIives\b', r'lives'])
line_replace.append([r'\bIeave\b', r'leave'])
line_replace.append([r'\bIawyer\b', r'lawyer'])
line_replace.append([r'\bAIex\b', r'Alex'])
line_replace.append([r'\bIogs\b', r'logs'])
line_replace.append([r'\b(P|p)Ieasure\b', r'\1leasure'])
line_replace.append([r'\bIack\b', r'lack'])
line_replace.append([r'\bIove\b', r'love'])
line_replace.append([r'\bAIexandra\b', r'Alexandra'])
line_replace.append([r'\bIot\b', r'lot'])
line_replace.append([r'\bIanding\b', r'landing'])
line_replace.append([r'\bThey\'II\b', r'They\'ll'])
line_replace.append([r'\bIet\'s\b', r'let\'s'])
line_replace.append([r'\bIand\b', r'land'])
line_replace.append([r'\bIying\b', r'lying'])
line_replace.append([r'\bIist\b', r'list'])
line_replace.append([r'\bAIIow\b', r'Allow'])
line_replace.append([r'\bIoved\b', r'loved'])
line_replace.append([r'\bIoss\b', r'loss'])
line_replace.append([r'\bIied\b', r'lied'])
line_replace.append([r'\bIaugh\b', r'laugh'])
line_replace.append([r'\b(h|H)avert\b', r'\1aven\'t'])
line_replace.append([r'\b(w|W)asrt\b', r'\1asn\'t'])
line_replace.append([r'\b(d|D)oesrt\b', r'\1oesn\'t'])
line_replace.append([r'\b(d|D)ort\b', r'\1on\'t'])
line_replace.append([r'\b(d|D)idrt\b', r'\1idn\'t'])
line_replace.append([r'\b(a|A)irt\b', r'\1in\'t'])
line_replace.append([r'\b(i|I)srt\b', r'\1sn\'t'])
line_replace.append([r'\b(w|W)ort\b', r'\1on\'t'])
line_replace.append([r'\b(c|C|w|W|s|S)ouldrt\b', r'\1ouldn\'t'])
line_replace.append([r'\barert\b', r'aren\'t'])
line_replace.append([r'\bls\b', r'Is'])
line_replace.append([r'\bLf\b', r'If'])
line_replace.append([r'\blf\b', r'If'])
line_replace.append([r'\blt\b', r'It'])
line_replace.append([r'\blt\'s\b', r'It\'s'])
line_replace.append([r'\bl\'m\b', r'I\'m'])
line_replace.append([r'\bl\'ll\b', r'I\'ll'])
line_replace.append([r'\bl\'ve\b', r'I\'ve'])
line_replace.append([r'\bl\b', r'I'])
line_replace.append([r'\bln\b', r'In'])
line_replace.append([r'\blmpossible\b', r'Impossible'])
line_replace.append([r'\bIight\b', r'light'])
line_replace.append([r'\bIevitation\b', r'levitation'])
line_replace.append([r'\bIeaving\b', r'leaving'])
line_replace.append([r'\bIooked\b', r'looked'])
line_replace.append([r'\bwe\'II\b', r'we\'ll'])
line_replace.append([r'\bIucky\b', r'lucky'])
line_replace.append([r'\bIuck\b', r'luck'])
line_replace.append([r'\bIater\b', r'later'])
line_replace.append([r'\bIift\b', r'lift'])
line_replace.append([r'\bIip\b', r'lip'])
line_replace.append([r'\bhe\'II\b', r'he\'ll'])
line_replace.append([r'\b(A|a)Iso\b', r'\1lso'])
line_replace.append([r'\bIooks\b', r'looks'])
line_replace.append([r'\b(P|p)Iayed\b', r'\1layed'])
line_replace.append([r'\bIaid\b', r'laid'])
line_replace.append([r'\bIikely\b', r'likely'])
line_replace.append([r'\bIow\b', r'low'])
line_replace.append([r'\bIeast\b', r'least'])
line_replace.append([r'\bIeader\b', r'leader'])
line_replace.append([r'\bIocate\b', r'locate'])
line_replace.append([r'\bIaw\b', r'law'])
line_replace.append([r'\bIately\b', r'lately'])
line_replace.append([r'\bFIying\b', r'Flying'])
line_replace.append([r'\bIiar\b', r'liar'])
line_replace.append([r'\b(s|S)chooI\b', r'\1chool'])
line_replace.append([r'\b(s|S)eriousIy\b', r'\1eriously'])
line_replace.append([r'\bIate\b', r'late'])
line_replace.append([r'\b(S|s)urgicaI\b', r'\1urgical'])
line_replace.append([r'\b(B|b)Iood\b', r'\1lood'])
line_replace.append([r'\b(f|F)eeIs\b', r'\1eels'])
line_replace.append([r'\b(S|s)Iept\b', r'\1lept'])
line_replace.append([r'\b(b|B)Iew\b', r'\1lew'])
line_replace.append([r'\b(T|t)aiI\b', r'\1ail'])
line_replace.append([r'\b(N|n)earIy\b', r'\1early'])
line_replace.append([r'\b(C|c)Iose\b', r'\1lose'])
line_replace.append([r'\b(C|c)Ioser\b', r'\1loser'])
line_replace.append([r'\b(E|e)viI\b', r'\1vil'])
line_replace.append([r'\b(M|m)odeI\b', r'\1odel'])
line_replace.append([r'\b(S|s)yphiIis\b', r'\1yphilis'])
line_replace.append([r'\b(R|r)eIationship\b', r'\1elationship'])
line_replace.append([r'\b(F|f)aIIing\b', r'\1alling'])
line_replace.append([r'\b(P|p)eopIe\b', r'\1eople'])
line_replace.append([r'\b(C|c|B|b)aII\b', r'\1all'])
line_replace.append([r'\b(W|w)ouId\b', r'\1ould'])
line_replace.append([r'\b(A|a)ppIe\b', r'\1pple'])
line_replace.append([r'\b(F|f)amiIiar\b', r'\1amiliar'])
line_replace.append([r'\b(R|r)eaIIy\b', r'\1eally'])
line_replace.append([r'\b(W|w|H|h|Y|y)eII\b', r'\1ell'])
line_replace.append([r'\b(P|p)robIem\b', r'\1roblem'])
line_replace.append([r'\bIonger\b', r'longer'])
line_replace.append([r'\b(G|g)irIfriend\b', r'\1irlfriend'])
line_replace.append([r'\b(F|f)Iew\b', r'\1lew'])
line_replace.append([r'\b(R|r)eaIize\b', r'\1ealize'])
line_replace.append([r'\bIive\b', r'live'])
line_replace.append([r'\b(S|s)tiII\b', r'\1till'])
line_replace.append([r'\b(W|w)iII\b', r'\1ill'])
line_replace.append([r'\bRusseII\b', r'Russell'])
line_replace.append([r'\b(S|s)maII\b', r'\1mall'])
line_replace.append([r'^[-\s]*$', r''])

line_remove = list()
line_remove.append(ur'^[-\s]*$')
line_remove.append(ur'\bswsub\b')
line_remove.append(ur'\bresync\b')
line_remove.append(ur'cync\sby\slanmao')
line_remove.append(ur'www\.1000fr\.com')
line_remove.append(ur'www\.tvsubtitles\.net')
line_remove.append(ur'YTET-Vicky8800')
line_remove.append(ur'www\.ydy\.com/bbs')
line_remove.append(ur'sync:gagegao')
line_remove.append(ur'FRM-lanma')
line_remove.append(ur'nowa\swizja')
line_remove.append(ur'ssmink')
line_remove.append(ur'תורגם על ידי')
line_remove.append(ur':תרגום')
line_remove.append(ur'\bLiNX\b')
line_remove.append(ur'(T|t)orec')
line_remove.append(ur'\byanx26\b')
line_remove.append(ur'הודה בוז')
line_remove.append(ur'\bGreenScorpion\b')
line_remove.append(ur'\bNeoTrix\b')
line_remove.append(ur'\bQsubs\b')
line_remove.append(ur'סונכרן')
line_remove.append(ur'\bglfinish\b')
line_remove.append(ur'\bShloogy\b')
line_remove.append(ur'עמוס נמני')
line_remove.append(ur'\.co\.il')
line_remove.append(ur'\bY0NaTaN\b')
line_remove.append(ur'מוקדש לך')
line_remove.append(ur'אינדיאנית שלי')
line_remove.append(ur'יומולדת שמח')
line_remove.append(ur'\beLAD\b')
line_remove.append(ur'תורגם ע"י')
line_remove.append(ur'מונחים רפואיים - ג\'ון דו')
line_remove.append(ur'מפורום תפוז')
line_remove.append(ur'סנכרן לגרסה זו')
line_remove.append(ur'מוקדש לפולי שלי')
line_remove.append(ur'sratim')
line_remove.append(ur'Donkey Cr3w')
line_remove.append(ur'R-Subs')
line_remove.append(ur'\[D-S\]')
line_remove.append(ur'ponkoit')
line_remove.append(ur'תורגם משמיעה')
line_remove.append(ur'י ביצה קשה')
line_remove.append(ur'כתובית זו הובאה')
line_remove.append(ur'שופצה, נערכה וסונכרנה לגרסה זו')
line_remove.append(ur':כתוביות')
line_remove.append(ur'\bsubbie\b')
line_remove.append(ur'\bXsesA\b')
line_remove.append(ur'Napisy pobrane')
line_remove.append(ur'קריעה וסינכרון')
line_remove.append(ur'^ב$')
line_remove.append(ur'^בי$')
line_remove.append(ur'^ביצ$')
line_remove.append(ur'^ביצה$')
line_remove.append(ur'^ביצה ק$')
line_remove.append(ur'^ביצה קש$')
line_remove.append(ur'^ביצה קשה$')
line_remove.append(ur'\bphaelox\b')
line_remove.append(ur'divxstation')
line_remove.append(ur'\bPetaBit\b')
line_remove.append(ur'\bRONKEY\b')
line_remove.append(ur'^בלעדית עבור$')
line_remove.append(ur'כתוביות ע"י')
line_remove.append(ur'chococat3@walla')
line_remove.append(ur'מוקדש לכל אוהבי האוס אי שם')
line_remove.append(ur'\bDrSub\b')
line_remove.append(ur'\bEliavgold\b')
line_remove.append(ur'^Elvira$')
line_remove.append(ur'ברוכה הבאה אלוירה')
line_remove.append(ur'לצוות מתרגמי האוס')
line_remove.append(ur'אלוירה ברוכה הבאה')
line_remove.append(ur'\bLob93\b')
line_remove.append(ur'הורד מהאתר')
line_remove.append(ur'על ההגהה Workbook')
line_remove.append(ur'\bElvir\b')
line_remove.append(ur'\boofir\b')
line_remove.append(ur'תוקן על ידי')
line_remove.append(ur'תורגם על-ידי')
line_remove.append(ur'תורגם ע"י')
line_remove.append(ur'תוקן ע"י')
line_remove.append(ur'תוקן קלות ע"י')
line_remove.append(ur'\bKROK\b')
line_remove.append(ur'\bQsubd\b')
line_remove.append(ur'\bQSubs\b')
line_remove.append(ur'\bAriel046\b')
line_remove.append(ur'סונכרן לגירסא זו ע"י')
line_remove.append(ur'\bZIPC\b')
line_remove.append(ur'\bTecNodRom\b')
line_remove.append(ur'www\.(T|t)orec\.(N|n)et')
line_remove.append(ur'\bמצוות פושל\b')
line_remove.append(ur'Visiontext Subtitles')
line_remove.append(ur'ENGLISH SDH')
line_remove.append(ur'ערן טלמור')
line_remove.append(ur'תרגום: שמעון אברג\'יל')
line_remove.append(ur'Srulikg')
line_remove.append(ur'ליונהארט')
line_remove.append(ur'תרגום: רותם ושמעון')
line_remove.append(ur'תרגום: קובי אלמוזנינו')
line_remove.append(ur'LH Translators Team')
line_remove.append(ur'שיפוץ: השייח\' הסעודי')
line_remove.append(ur'שופץ ע"י השייח\' הסעודי')
line_remove.append(ur'תרגום: שמעון ורותם אברג\'יל')
line_remove.append(ur'^עריכה לשונית$')
line_remove.append(ur'-= Sub-Zero =-')
line_remove.append(ur'-= SUB-ZERO-=')
line_remove.append(ur'Lionetwork')
line_remove.append(ur'תרגום זה בוצע על ידי')
line_remove.append(ur'(D|d)(-|a)k(w|W)arez')
line_remove.append(ur'תרגום זה נעשה על ידי')
line_remove.append(ur'--תורגם עם הרבה זיעה על ידי--')
line_remove.append(ur'תורגם מספרדית ע"י אסף פארי')
line_remove.append(ur'^EriC$')
line_remove.append(ur'SubZ3ro')
line_remove.append(ur'TheTerminator נערך ותוקן בשיתוף עם')
line_remove.append(ur'התרגום נעשה על ידי המוריד')
line_remove.append(ur'^David-Z$')
line_remove.append(ur'(D|d)r(Z|z)iv@(Y|y)ahoo')
line_remove.append(ur'ELRAN_O')
line_remove.append(ur'MCsnagel')
line_remove.append(ur'הגהה וסנכרון ע"י')
line_remove.append(ur'ialfan-ו mb0:עברית')
line_remove.append(ur'תורגם וסונוכרן משמיעה ע"י')
line_remove.append(ur'\bOutwit\b')
line_remove.append(ur'^נקרע ותוקן$')
line_remove.append(ur'^תרגום: אבי דניאלי$')
line_remove.append(ur'^GimLY$')
line_remove.append(ur'^White Fang-תרגום: עמית יקיר ו$')
line_remove.append(ur'^.Shayx ע"י$')
line_remove.append(ur'\btinyurl\b')
line_remove.append(ur'\bצפייה מהנה\b')
line_remove.append(ur'\bצפיה מהנה\b')
line_remove.append(ur'\bFoxRiver\b')
line_remove.append(ur'^Extreme מקבוצת$')
line_remove.append(ur'\bextremesubs\b')
line_remove.append(ur'\bCiWaN\b')
line_remove.append(ur'\bNata4ever\b')
line_remove.append(ur'\bYosefff\b')
line_remove.append(ur'\bassem נקרע ע"י\b')
line_remove.append(ur'\bKawa: סנכרון\b')
line_remove.append(ur'\bHentaiman\b')
line_remove.append(ur'\bfoxi9\b')
line_remove.append(ur'\b-תודה מיוחדת ל\b')
line_remove.append(ur'\bGamby\b')
line_remove.append(ur'\bBrassica nigra\b')
line_remove.append(ur'\bqsubs\b')
line_remove.append(ur'\bעדי-בלי-בצל\b')
line_remove.append(ur'\bבקרו אותנו בפורום\b')
line_remove.append(ur'\bShareTW\b')
line_remove.append(ur'\bSeretHD\b')
line_remove.append(ur'\b[A-Za-z0-9\.]+@gmail.\s*com\b')
line_remove.append(ur'אוהבים את התרגומים שלנו')
line_remove.append(ur'נקלענו למאבק')
line_remove.append(ur'משפטי מתמשך')
line_remove.append(ur'לבילד המתקשה בהבנת קרדיטים')
line_remove.append(ur'אנא תרמו לנו כדי')
line_remove.append(ur'שנוכל להמשיך לתרגם')
line_remove.append(ur':לפרטים')
line_remove.append(ur'הגהה על-ידי')
line_remove.append(ur'HAZY7868')
line_remove.append(ur'^[-\s]*$')