# -*- coding: utf-8 -*-
subtitle_filter = dict()
subtitle_filter['remove block'] = list()
subtitle_filter['remove line'] = list()
subtitle_filter['replace'] = list()


subtitle_filter['replace'].append([r'\b *(,|\.|\?|%|!|\$) *\b', r'\1 '])
subtitle_filter['replace'].append([r'\.\s*\.\s*\.\.?', r'...'])
subtitle_filter['replace'].append([r'</?[a-z]+/?>', r''])
subtitle_filter['replace'].append([r'\'{2}', r'"'])
subtitle_filter['replace'].append([r'\s+\)', r')'])
subtitle_filter['replace'].append([r'\(\s+', '('])
subtitle_filter['replace'].append([r'\s+\]', r']'])
subtitle_filter['replace'].append([r'\[\s+', '['])
subtitle_filter['replace'].append([r'\[[^\]]+\]\s*', r''])
subtitle_filter['replace'].append([r'^[^\]]+\]', r''])
subtitle_filter['replace'].append([r'\[[^\]]+\$', r''])
subtitle_filter['replace'].append([r'\([A-Z0-9l\s]+\)', r''])
subtitle_filter['replace'].append([r'\([A-Z0-9l\s]+$', r''])
subtitle_filter['replace'].append([r'^[A-Z0-9l\s]+\)', r''])
subtitle_filter['replace'].append([r'\b[-A-Z0-9\s]+:\s*', r''])
subtitle_filter['replace'].append([r'Theysaid', r'They said'])
subtitle_filter['replace'].append([r'\bIast\b', r'last'])
subtitle_filter['replace'].append([r'\bIook\b', r'look'])
subtitle_filter['replace'].append([r'\bIetting\b', r'letting'])
subtitle_filter['replace'].append([r'\bIet\b', r'let'])
subtitle_filter['replace'].append([r'\bshe\'II\b', r'she\'ll'])
subtitle_filter['replace'].append([r'\bIooking\b', r'looking'])
subtitle_filter['replace'].append([r'\bIife\b', r'life'])
subtitle_filter['replace'].append([r'\bIeft\b', r'left'])
subtitle_filter['replace'].append([r'\bIike\b', r'like'])
subtitle_filter['replace'].append([r'\bIittle\b', r'little'])
subtitle_filter['replace'].append([r'\b(P|p)Iease\b', r'\1lease'])
subtitle_filter['replace'].append([r'\bIadies\b', r'ladies'])
subtitle_filter['replace'].append([r'\bIearn\b', r'learn'])
subtitle_filter['replace'].append([r'\bIanded\b', r'landed'])
subtitle_filter['replace'].append([r'\bIocked\b', r'locked'])
subtitle_filter['replace'].append([r'\bIie\b', r'lie'])
subtitle_filter['replace'].append([r'\bCIaire\b', r'Claire'])
subtitle_filter['replace'].append([r'\bIong\b', r'long'])
subtitle_filter['replace'].append([r'\bIine\b', r'line'])
subtitle_filter['replace'].append([r'\byou\'II\b', r'you\'ll'])
subtitle_filter['replace'].append([r'\bIives\b', r'lives'])
subtitle_filter['replace'].append([r'\bIeave\b', r'leave'])
subtitle_filter['replace'].append([r'\bIawyer\b', r'lawyer'])
subtitle_filter['replace'].append([r'\bAIex\b', r'Alex'])
subtitle_filter['replace'].append([r'\bIogs\b', r'logs'])
subtitle_filter['replace'].append([r'\b(P|p)Ieasure\b', r'\1leasure'])
subtitle_filter['replace'].append([r'\bIack\b', r'lack'])
subtitle_filter['replace'].append([r'\bIove\b', r'love'])
subtitle_filter['replace'].append([r'\bAIexandra\b', r'Alexandra'])
subtitle_filter['replace'].append([r'\bIot\b', r'lot'])
subtitle_filter['replace'].append([r'\bIanding\b', r'landing'])
subtitle_filter['replace'].append([r'\bThey\'II\b', r'They\'ll'])
subtitle_filter['replace'].append([r'\bIet\'s\b', r'let\'s'])
subtitle_filter['replace'].append([r'\bIand\b', r'land'])
subtitle_filter['replace'].append([r'\bIying\b', r'lying'])
subtitle_filter['replace'].append([r'\bIist\b', r'list'])
subtitle_filter['replace'].append([r'\bAIIow\b', r'Allow'])
subtitle_filter['replace'].append([r'\bIoved\b', r'loved'])
subtitle_filter['replace'].append([r'\bIoss\b', r'loss'])
subtitle_filter['replace'].append([r'\bIied\b', r'lied'])
subtitle_filter['replace'].append([r'\bIaugh\b', r'laugh'])
subtitle_filter['replace'].append([r'\bpIace\b', r'place'])
subtitle_filter['replace'].append([r'\b(h|H)avert\b', r'\1aven\'t'])
subtitle_filter['replace'].append([r'\b(w|W)asrt\b', r'\1asn\'t'])
subtitle_filter['replace'].append([r'\b(d|D)oesrt\b', r'\1oesn\'t'])
subtitle_filter['replace'].append([r'\b(d|D)ort\b', r'\1on\'t'])
subtitle_filter['replace'].append([r'\b(d|D)idrt\b', r'\1idn\'t'])
subtitle_filter['replace'].append([r'\b(a|A)irt\b', r'\1in\'t'])
subtitle_filter['replace'].append([r'\b(i|I)srt\b', r'\1sn\'t'])
subtitle_filter['replace'].append([r'\b(w|W)ort\b', r'\1on\'t'])
subtitle_filter['replace'].append([r'\b(c|C|w|W|s|S)ouldrt\b', r'\1ouldn\'t'])
subtitle_filter['replace'].append([r'\barert\b', r'aren\'t'])
subtitle_filter['replace'].append([r'\bls\b', r'Is'])
subtitle_filter['replace'].append([r'\bLf\b', r'If'])
subtitle_filter['replace'].append([r'\blf\b', r'If'])
subtitle_filter['replace'].append([r'\blt\b', r'It'])
subtitle_filter['replace'].append([r'\blt\'s\b', r'It\'s'])
subtitle_filter['replace'].append([r'\bl\'m\b', r'I\'m'])
subtitle_filter['replace'].append([r'\bl\'ll\b', r'I\'ll'])
subtitle_filter['replace'].append([r'\bl\'ve\b', r'I\'ve'])
subtitle_filter['replace'].append([r'\bl\b', r'I'])
subtitle_filter['replace'].append([r'\bln\b', r'In'])
subtitle_filter['replace'].append([r'\blmpossible\b', r'Impossible'])
subtitle_filter['replace'].append([r'\bIight\b', r'light'])
subtitle_filter['replace'].append([r'\bIevitation\b', r'levitation'])
subtitle_filter['replace'].append([r'\bIeaving\b', r'leaving'])
subtitle_filter['replace'].append([r'\bIooked\b', r'looked'])
subtitle_filter['replace'].append([r'\bwe\'II\b', r'we\'ll'])
subtitle_filter['replace'].append([r'\bIucky\b', r'lucky'])
subtitle_filter['replace'].append([r'\bIuck\b', r'luck'])
subtitle_filter['replace'].append([r'\bIater\b', r'later'])
subtitle_filter['replace'].append([r'\bIift\b', r'lift'])
subtitle_filter['replace'].append([r'\bIip\b', r'lip'])
subtitle_filter['replace'].append([r'\bhe\'II\b', r'he\'ll'])
subtitle_filter['replace'].append([r'\b(A|a)Iso\b', r'\1lso'])
subtitle_filter['replace'].append([r'\bIooks\b', r'looks'])
subtitle_filter['replace'].append([r'\b(P|p)Iayed\b', r'\1layed'])
subtitle_filter['replace'].append([r'\bIaid\b', r'laid'])
subtitle_filter['replace'].append([r'\bIikely\b', r'likely'])
subtitle_filter['replace'].append([r'\bIow\b', r'low'])
subtitle_filter['replace'].append([r'\bIeast\b', r'least'])
subtitle_filter['replace'].append([r'\bIeader\b', r'leader'])
subtitle_filter['replace'].append([r'\bIocate\b', r'locate'])
subtitle_filter['replace'].append([r'\bIaw\b', r'law'])
subtitle_filter['replace'].append([r'\bIately\b', r'lately'])
subtitle_filter['replace'].append([r'\bFIying\b', r'Flying'])
subtitle_filter['replace'].append([r'\bIiar\b', r'liar'])
subtitle_filter['replace'].append([r'\b(s|S)chooI\b', r'\1chool'])
subtitle_filter['replace'].append([r'\b(s|S)eriousIy\b', r'\1eriously'])
subtitle_filter['replace'].append([r'\bIate\b', r'late'])
subtitle_filter['replace'].append([r'\b(S|s)urgicaI\b', r'\1urgical'])
subtitle_filter['replace'].append([r'\b(B|b)Iood\b', r'\1lood'])
subtitle_filter['replace'].append([r'\b(f|F)eeIs\b', r'\1eels'])
subtitle_filter['replace'].append([r'\b(S|s)Iept\b', r'\1lept'])
subtitle_filter['replace'].append([r'\b(b|B)Iew\b', r'\1lew'])
subtitle_filter['replace'].append([r'\b(T|t)aiI\b', r'\1ail'])
subtitle_filter['replace'].append([r'\b(N|n)earIy\b', r'\1early'])
subtitle_filter['replace'].append([r'\b(C|c)Iose\b', r'\1lose'])
subtitle_filter['replace'].append([r'\b(C|c)Ioser\b', r'\1loser'])
subtitle_filter['replace'].append([r'\b(E|e)viI\b', r'\1vil'])
subtitle_filter['replace'].append([r'\b(M|m)odeI\b', r'\1odel'])
subtitle_filter['replace'].append([r'\b(S|s)yphiIis\b', r'\1yphilis'])
subtitle_filter['replace'].append([r'\b(R|r)eIationship\b', r'\1elationship'])
subtitle_filter['replace'].append([r'\b(F|f)aIIing\b', r'\1alling'])
subtitle_filter['replace'].append([r'\b(P|p)eopIe\b', r'\1eople'])
subtitle_filter['replace'].append([r'\b(C|c|B|b)aII\b', r'\1all'])
subtitle_filter['replace'].append([r'\b(W|w)ouId\b', r'\1ould'])
subtitle_filter['replace'].append([r'\b(A|a)ppIe\b', r'\1pple'])
subtitle_filter['replace'].append([r'\b(F|f)amiIiar\b', r'\1amiliar'])
subtitle_filter['replace'].append([r'\b(R|r)eaIIy\b', r'\1eally'])
subtitle_filter['replace'].append([r'\b(W|w|H|h|Y|y)eII\b', r'\1ell'])
subtitle_filter['replace'].append([r'\b(P|p)robIem\b', r'\1roblem'])
subtitle_filter['replace'].append([r'\bIonger\b', r'longer'])
subtitle_filter['replace'].append([r'\b(G|g)irIfriend\b', r'\1irlfriend'])
subtitle_filter['replace'].append([r'\b(F|f)Iew\b', r'\1lew'])
subtitle_filter['replace'].append([r'\b(R|r)eaIize\b', r'\1ealize'])
subtitle_filter['replace'].append([r'\bIive\b', r'live'])
subtitle_filter['replace'].append([r'\b(S|s)tiII\b', r'\1till'])
subtitle_filter['replace'].append([r'\b(W|w)iII\b', r'\1ill'])
subtitle_filter['replace'].append([r'\bRusseII\b', r'Russell'])
subtitle_filter['replace'].append([r'\b(S|s)maII\b', r'\1mall'])
subtitle_filter['replace'].append([r'^[-\s]*$', r''])


subtitle_filter['remove line'].append(ur'^[-\s]*$')
subtitle_filter['remove line'].append(ur'\bswsub\b')
subtitle_filter['remove line'].append(ur'\bresync\b')
subtitle_filter['remove line'].append(ur'cync\sby\slanmao')
subtitle_filter['remove line'].append(ur'www\.1000fr\.com')
subtitle_filter['remove line'].append(ur'www\.tvsubtitles\.net')
subtitle_filter['remove line'].append(ur'YTET-Vicky8800')
subtitle_filter['remove line'].append(ur'www\.ydy\.com/bbs')
subtitle_filter['remove line'].append(ur'sync:gagegao')
subtitle_filter['remove line'].append(ur'FRM-lanma')
subtitle_filter['remove line'].append(ur'nowa\swizja')
subtitle_filter['remove line'].append(ur'ssmink')
subtitle_filter['remove line'].append(ur'תורגם על ידי')
subtitle_filter['remove line'].append(ur':תרגום')
subtitle_filter['remove line'].append(ur'\bLiNX\b')
subtitle_filter['remove line'].append(ur'(T|t)orec')
subtitle_filter['remove line'].append(ur'\byanx26\b')
subtitle_filter['remove line'].append(ur'הודה בוז')
subtitle_filter['remove line'].append(ur'\bGreenScorpion\b')
subtitle_filter['remove line'].append(ur'\bNeoTrix\b')
subtitle_filter['remove line'].append(ur'\bQsubs\b')
subtitle_filter['remove line'].append(ur'סונכרן')
subtitle_filter['remove line'].append(ur'\bglfinish\b')
subtitle_filter['remove line'].append(ur'\bShloogy\b')
subtitle_filter['remove line'].append(ur'עמוס נמני')
subtitle_filter['remove line'].append(ur'\.co\.il')
subtitle_filter['remove line'].append(ur'\bY0NaTaN\b')
subtitle_filter['remove line'].append(ur'מוקדש לך')
subtitle_filter['remove line'].append(ur'אינדיאנית שלי')
subtitle_filter['remove line'].append(ur'יומולדת שמח')
subtitle_filter['remove line'].append(ur'\beLAD\b')
subtitle_filter['remove line'].append(ur'תורגם ע"י')
subtitle_filter['remove line'].append(ur'מונחים רפואיים - ג\'ון דו')
subtitle_filter['remove line'].append(ur'מפורום תפוז')
subtitle_filter['remove line'].append(ur'סנכרן לגרסה זו')
subtitle_filter['remove line'].append(ur'מוקדש לפולי שלי')
subtitle_filter['remove line'].append(ur'sratim')
subtitle_filter['remove line'].append(ur'Donkey Cr3w')
subtitle_filter['remove line'].append(ur'R-Subs')
subtitle_filter['remove line'].append(ur'\[D-S\]')
subtitle_filter['remove line'].append(ur'ponkoit')
subtitle_filter['remove line'].append(ur'תורגם משמיעה')
subtitle_filter['remove line'].append(ur'י ביצה קשה')
subtitle_filter['remove line'].append(ur'כתובית זו הובאה')
subtitle_filter['remove line'].append(ur'שופצה, נערכה וסונכרנה לגרסה זו')
subtitle_filter['remove line'].append(ur':כתוביות')
subtitle_filter['remove line'].append(ur'\bsubbie\b')
subtitle_filter['remove line'].append(ur'\bXsesA\b')
subtitle_filter['remove line'].append(ur'Napisy pobrane')
subtitle_filter['remove line'].append(ur'קריעה וסינכרון')
subtitle_filter['remove line'].append(ur'^ב$')
subtitle_filter['remove line'].append(ur'^בי$')
subtitle_filter['remove line'].append(ur'^ביצ$')
subtitle_filter['remove line'].append(ur'^ביצה$')
subtitle_filter['remove line'].append(ur'^ביצה ק$')
subtitle_filter['remove line'].append(ur'^ביצה קש$')
subtitle_filter['remove line'].append(ur'^ביצה קשה$')
subtitle_filter['remove line'].append(ur'\bphaelox\b')
subtitle_filter['remove line'].append(ur'divxstation')
subtitle_filter['remove line'].append(ur'\bPetaBit\b')
subtitle_filter['remove line'].append(ur'\bRONKEY\b')
subtitle_filter['remove line'].append(ur'^בלעדית עבור$')
subtitle_filter['remove line'].append(ur'כתוביות ע"י')
subtitle_filter['remove line'].append(ur'chococat3@walla')
subtitle_filter['remove line'].append(ur'מוקדש לכל אוהבי האוס אי שם')
subtitle_filter['remove line'].append(ur'\bDrSub\b')
subtitle_filter['remove line'].append(ur'\bEliavgold\b')
subtitle_filter['remove line'].append(ur'^Elvira$')
subtitle_filter['remove line'].append(ur'ברוכה הבאה אלוירה')
subtitle_filter['remove line'].append(ur'לצוות מתרגמי האוס')
subtitle_filter['remove line'].append(ur'אלוירה ברוכה הבאה')
subtitle_filter['remove line'].append(ur'\bLob93\b')
subtitle_filter['remove line'].append(ur'הורד מהאתר')
subtitle_filter['remove line'].append(ur'על ההגהה Workbook')
subtitle_filter['remove line'].append(ur'\bElvir\b')
subtitle_filter['remove line'].append(ur'\boofir\b')
subtitle_filter['remove line'].append(ur'תוקן על ידי')
subtitle_filter['remove line'].append(ur'תורגם על-ידי')
subtitle_filter['remove line'].append(ur'תורגם ע"י')
subtitle_filter['remove line'].append(ur'תוקן ע"י')
subtitle_filter['remove line'].append(ur'תוקן קלות ע"י')
subtitle_filter['remove line'].append(ur'\bKROK\b')
subtitle_filter['remove line'].append(ur'\bQsubd\b')
subtitle_filter['remove line'].append(ur'\bQSubs\b')
subtitle_filter['remove line'].append(ur'\bAriel046\b')
subtitle_filter['remove line'].append(ur'סונכרן לגירסא זו ע"י')
subtitle_filter['remove line'].append(ur'\bZIPC\b')
subtitle_filter['remove line'].append(ur'\bTecNodRom\b')
subtitle_filter['remove line'].append(ur'www\.(T|t)orec\.(N|n)et')
subtitle_filter['remove line'].append(ur'\bמצוות פושל\b')
subtitle_filter['remove line'].append(ur'Visiontext Subtitles')
subtitle_filter['remove line'].append(ur'ENGLISH SDH')
subtitle_filter['remove line'].append(ur'ערן טלמור')
subtitle_filter['remove line'].append(ur'תרגום: שמעון אברג\'יל')
subtitle_filter['remove line'].append(ur'Srulikg')
subtitle_filter['remove line'].append(ur'ליונהארט')
subtitle_filter['remove line'].append(ur'תרגום: רותם ושמעון')
subtitle_filter['remove line'].append(ur'תרגום: קובי אלמוזנינו')
subtitle_filter['remove line'].append(ur'LH Translators Team')
subtitle_filter['remove line'].append(ur'שיפוץ: השייח\' הסעודי')
subtitle_filter['remove line'].append(ur'שופץ ע"י השייח\' הסעודי')
subtitle_filter['remove line'].append(ur'תרגום: שמעון ורותם אברג\'יל')
subtitle_filter['remove line'].append(ur'^עריכה לשונית$')
subtitle_filter['remove line'].append(ur'-= Sub-Zero =-')
subtitle_filter['remove line'].append(ur'-= SUB-ZERO-=')
subtitle_filter['remove line'].append(ur'Lionetwork')
subtitle_filter['remove line'].append(ur'תרגום זה בוצע על ידי')
subtitle_filter['remove line'].append(ur'(D|d)(-|a)k(w|W)arez')
subtitle_filter['remove line'].append(ur'תרגום זה נעשה על ידי')
subtitle_filter['remove line'].append(ur'--תורגם עם הרבה זיעה על ידי--')
subtitle_filter['remove line'].append(ur'תורגם מספרדית ע"י אסף פארי')
subtitle_filter['remove line'].append(ur'^EriC$')
subtitle_filter['remove line'].append(ur'SubZ3ro')
subtitle_filter['remove line'].append(ur'TheTerminator נערך ותוקן בשיתוף עם')
subtitle_filter['remove line'].append(ur'התרגום נעשה על ידי המוריד')
subtitle_filter['remove line'].append(ur'^David-Z$')
subtitle_filter['remove line'].append(ur'(D|d)r(Z|z)iv@(Y|y)ahoo')
subtitle_filter['remove line'].append(ur'ELRAN_O')
subtitle_filter['remove line'].append(ur'MCsnagel')
subtitle_filter['remove line'].append(ur'הגהה וסנכרון ע"י')
subtitle_filter['remove line'].append(ur'ialfan-ו mb0:עברית')
subtitle_filter['remove line'].append(ur'תורגם וסונוכרן משמיעה ע"י')
subtitle_filter['remove line'].append(ur'\bOutwit\b')
subtitle_filter['remove line'].append(ur'^נקרע ותוקן$')
subtitle_filter['remove line'].append(ur'^תרגום: אבי דניאלי$')
subtitle_filter['remove line'].append(ur'^GimLY$')
subtitle_filter['remove line'].append(ur'^White Fang-תרגום: עמית יקיר ו$')
subtitle_filter['remove line'].append(ur'^.Shayx ע"י$')
subtitle_filter['remove line'].append(ur'\btinyurl\b')
subtitle_filter['remove line'].append(ur'\bצפייה מהנה\b')
subtitle_filter['remove line'].append(ur'\bצפיה מהנה\b')
subtitle_filter['remove line'].append(ur'\bFoxRiver\b')
subtitle_filter['remove line'].append(ur'^Extreme מקבוצת$')
subtitle_filter['remove line'].append(ur'\bextremesubs\b')
subtitle_filter['remove line'].append(ur'\bCiWaN\b')
subtitle_filter['remove line'].append(ur'\bNata4ever\b')
subtitle_filter['remove line'].append(ur'\bYosefff\b')
subtitle_filter['remove line'].append(ur'\bassem נקרע ע"י\b')
subtitle_filter['remove line'].append(ur'\bKawa: סנכרון\b')
subtitle_filter['remove line'].append(ur'\bHentaiman\b')
subtitle_filter['remove line'].append(ur'\bfoxi9\b')
subtitle_filter['remove line'].append(ur'\b-תודה מיוחדת ל\b')
subtitle_filter['remove line'].append(ur'\bGamby\b')
subtitle_filter['remove line'].append(ur'\bBrassica nigra\b')
subtitle_filter['remove line'].append(ur'\bqsubs\b')
subtitle_filter['remove line'].append(ur'\bעדי-בלי-בצל\b')
subtitle_filter['remove line'].append(ur'\bבקרו אותנו בפורום\b')
subtitle_filter['remove line'].append(ur'\bShareTW\b')
subtitle_filter['remove line'].append(ur'\bSeretHD\b')
subtitle_filter['remove line'].append(ur'\b[A-Za-z0-9\.]+@gmail.\s*com\b')
subtitle_filter['remove line'].append(ur'אוהבים את התרגומים שלנו')
subtitle_filter['remove line'].append(ur'נקלענו למאבק')
subtitle_filter['remove line'].append(ur'משפטי מתמשך')
subtitle_filter['remove line'].append(ur'לבילד המתקשה בהבנת קרדיטים')
subtitle_filter['remove line'].append(ur'אנא תרמו לנו כדי')
subtitle_filter['remove line'].append(ur'שנוכל להמשיך לתרגם')
subtitle_filter['remove line'].append(ur':לפרטים')
subtitle_filter['remove line'].append(ur'הגהה על-ידי')
subtitle_filter['remove line'].append(ur'HAZY7868')
subtitle_filter['remove line'].append(ur'^[-\s]*$')